// import 'dart:io';
// import 'dart:async';
// import 'dart:typed_data';
// import 'package:http/http.dart' as http;
// import 'package:intl/intl.dart';
// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// import 'package:path_provider/path_provider.dart' as path_provider;
// import 'package:connectivity_plus/connectivity_plus.dart';
// import 'package:path_provider/path_provider.dart';
// import 'package:uuid/uuid.dart';
// import 'package:firebase_storage/firebase_storage.dart';
// import 'package:marverick/models/form.dart' as f;
// import 'package:marverick/models/field.dart';
// import 'package:marverick/services/pdf.dart';
// import 'package:marverick/services/authen.dart';
// import 'package:marverick/services/database.dart';
// import 'package:marverick/ui/views/input.dart';
// import 'package:marverick/utils/constants.dart';
// import 'package:marverick/utils/utils.dart';
//
// ///-------------------------------------------------------------------------
// ///PPC FORM
// ///-------------------------------------------------------------------------
// static f.Form initPpcCheck() {
// DateTime timeStamp = DateTime.now();
//
// List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
// List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
// int gradeCommentMaxLen = 190;
//
// return f.Form(
// type: f.FormType.ppc,
// formName: 'PPC',
// createDateTime: timeStamp,
// createBy: Authen.user != null ? Authen.user.email : '',
// id: uuid.v1(),
// filePath: 'forms/ppc.pdf',
// dbTable: kPPCTable,
// fontSize: 9,
// sectionLabel: [
// 'Personal Detail',
// 'Check Detail',
// 'Grading',
// 'Number of Manual Landing and Go-around',
// 'Competency Assessment and Comments',
// 'Result',
// 'Signature',
// ],
// gradeSectionLabel: [
// 'PRE-FLIGHT PREPARATION AND GROUND OPERATIONS',
// 'TAKEOFF',
// 'INSTRUMENT PROCEDURES AND NAVIGATION PROCEDURES',
// 'INFLIGHT MANEUVERS',
// 'APPROACH AND LANDING',
// 'OPERATIONS SPECIFICATION',
// 'Aircraft System Malfunction (Refer to PPC timeline, if applicable)',
// 'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
// 'NON-TECHNICAL',
// 'ADDITIONAL EXERCISES',
// ],
// formLabel: 'PPC',
// formLabelInfoField1: 'pilot_rank',
// formLabelInfoField2: 'pilot_name',
// fields: [
// ///.....................................................................
// ///TRAINEE
// ///.....................................................................
// Field(
// name: 'pilot_rank',
// label: 'Trainee\'s Rank',
// type: FieldType.radio,
// listValue: ['Capt.', 'SFO.', 'FO.'],
// section: 1,
// subSection: 1,
// page: 1,
// posXList: [130, 174, 220],
// posYList: [84, 84, 84]),
// Field(
// name: 'pilot_name',
// label: 'Trainee\'s Name',
// type: FieldType.string,
// section: 1,
// subSection: 1,
// // stringValue: 'Test',
// posX: 90,
// posY: 103),
// Field(
// name: 'pilot_license_no',
// label: 'Trainee\'s License No',
// type: FieldType.string,
// section: 1,
// subSection: 1,
// // stringValue: 'TH.FCL.0009999',
// posX: 358,
// posY: 87),
// Field(
// name: 'pilot_id',
// label: 'Trainee\'s Staff No(xxxx)',
// type: FieldType.string,
// section: 1,
// subSection: 1,
// keyboardType: TextInputType.number,
// // stringValue: '1234',
// posX: 380,
// posY: 103),
//
// ///.....................................................................
// ///INSTRUCTOR
// ///.....................................................................
// Field(
// name: 'instructor_rank',
// label: 'Instructor\'s Rank',
// type: FieldType.radio,
// listValue: ['CAPT'],
// // intValue: 0,
// section: 1,
// subSection: 2,
// page: 1,
// posXList: [130],
// posYList: [117]),
// Field(
// name: 'instructor_name',
// label: 'Instructor\'s Name',
// type: FieldType.string,
// section: 1,
// subSection: 2,
// // stringValue: 'Audrey H.',
// posX: 90,
// posY: 136),
// Field(
// name: 'instructor_cert_no',
// label: 'Ins Certificate No',
// type: FieldType.string,
// section: 1,
// subSection: 2,
// // stringValue: 'TH.FCL.0009999',
// posX: 358,
// posY: 120),
// Field(
// name: 'instructor_id',
// label: 'Instructor\'s Staff No(xxxx)',
// type: FieldType.string,
// section: 1,
// subSection: 2,
// keyboardType: TextInputType.number,
// // stringValue: '1123',
// posX: 380,
// posY: 136),
//
// ///.....................................................................
// ///Examiner
// ///.....................................................................
// Field(
// name: 'examiner_type',
// label: 'Examiner\'s Type',
// type: FieldType.radio,
// listValue: ['DCP', 'PCPS', 'CAAT'],
// // intValue: 0,
// section: 1,
// subSection: 3,
// page: 1,
// posXList: [130, 174, 220],
// posYList: [150, 150, 150]),
// Field(
// name: 'examiner_name',
// label: 'Examiner\'s Name',
// type: FieldType.string,
// section: 1,
// subSection: 3,
// // stringValue: 'David G.',
// posX: 90,
// posY: 169),
// Field(
// name: 'examiner_pel_no',
// label: 'PEL / CA No',
// type: FieldType.string,
// section: 1,
// subSection: 3,
// // stringValue: 'PEL123',
// posX: 358,
// posY: 153),
// Field(
// name: 'examiner_id',
// label: 'Examiner\'s Staff No(xxxx)',
// type: FieldType.string,
// section: 1,
// subSection: 3,
// keyboardType: TextInputType.number,
// // stringValue: '0055',
// posX: 380,
// posY: 169),
//
// ///.....................................................................
// ///CHECK DETAILS
// ///.....................................................................
// Field(
// name: 'check_date',
// label: 'Date',
// // type: FieldType.string,
// type: FieldType.date,
// page: 1,
// section: 2,
// subSection: 1,
// keyboardType: TextInputType.datetime,
// stringValue:
// DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
// dateTimeValue: DateTime.now(),
// posX: 506,
// posY: 87),
// Field(
// name: 'block_time',
// label: 'Block Time',
// type: FieldType.string,
// section: 2,
// subSection: 1,
// // stringValue: '04:00',
// posX: 506,
// posY: 103),
// Field(
// name: 'fstd_no',
// label: 'FSTD No.',
// type: FieldType.string,
// section: 2,
// subSection: 1,
// // stringValue: 'FSTD-012',
// posX: 506,
// posY: 120),
// Field(
// name: 'route',
// label: 'ROUTE',
// type: FieldType.string,
// section: 2,
// subSection: 1,
// // stringValue: 'VTBS-VTCC',
// posX: 506,
// posY: 136),
// Field(
// name: 'check_course',
// label: 'Training Course',
// type: FieldType.radio,
// listValue: [
// 'Initial Training',
// 'Conversion/Transition Training',
// 'New Entry On-Type Training',
// 'CCQ',
// 'Command Upgrade',
// 'Recurrent',
// ],
// // intValue: 5,
// section: 2,
// subSection: 2,
// page: 1,
// posXList: [44, 44, 44, 204, 204, 204],
// posYList: [208, 221, 235, 208, 221, 235]),
// Field(
// name: 'check_type',
// label: 'Type of Check',
// // type: FieldType.radio,
// type: FieldType.checkbox,
// listValue: [
// 'Pilot Proficiency Check (PPC) / Skill Test',
// 'Instrument Rating (IR)',
// 'Right Hand Seat (RHS)',
// ],
// checkBoxValue: [false, false, false],
// // intValue: 0,
// section: 2,
// subSection: 2,
// page: 1,
// posXList: [363, 363, 363],
// posYList: [208, 221, 235]),
// Field(
// name: 'check_type_0',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'check_type_1',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'check_type_2',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
//
// ///.....................................................................
// ///GRADING
// ///.....................................................................
// Field(
// name: 'a_1',
// label: 'Preflight Preparation',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 1,
// gradeSection: 1,
// posXList: _gradePosX,
// posYList: [308, 308, 308, 308, 308, 308]),
// Field(
// name: 'a_2_detail',
// label: 'Abnormal Engine Start ..........',
// type: FieldType.string,
// // stringValue: 'Hung Start',
// page: 1,
// section: 3,
// subSection: 1,
// gradeSection: 1,
// posX: 203,
// posY: 322),
// Field(
// name: 'a_2',
// label: 'Engine Start / Abnormal Engine Start …/ After Start',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 1,
// gradeSection: 1,
// posXList: _gradePosX,
// posYList: [322, 322, 322, 322, 322, 322]),
// Field(
// name: 'a_3',
// label: 'Taxiing',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 1,
// gradeSection: 1,
// posXList: _gradePosX,
// posYList: [336, 336, 336, 336, 336, 336]),
// Field(
// name: 'a_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 1,
// gradeSection: 1,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 310,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'b_4',
// label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// posXList: _gradePosX,
// posYList: [364, 364, 364, 364, 364, 364]),
// Field(
// name: 'b_5',
// label: 'Cross Wind Takeoff / Gusty Wind',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// posXList: _gradePosX,
// posYList: [378, 378, 378, 378, 378, 378]),
// Field(
// name: 'b_6',
// label: 'Windshear during Takeoff',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// posXList: _gradePosX,
// posYList: [392, 392, 392, 392, 392, 392]),
// Field(
// name: 'b_7',
// label: 'Rejected Takeoff',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// posXList: _gradePosX,
// posYList: [406, 406, 406, 406, 406, 406]),
// Field(
// name: 'b_8',
// label: 'Takeoff with Simulated Engine Failure at V2',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// posXList: _gradePosX,
// posYList: [420, 420, 420, 420, 420, 420]),
// Field(
// name: 'b_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 2,
// gradeSection: 2,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 366,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'c_9',
// label: 'SID - Standard Instrument Departure / RNAV SID',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [448, 448, 448, 448, 448, 448]),
// Field(
// name: 'c_10',
// label: 'STAR Standard Terminal Arrival Route / RNAV STAR',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [462, 462, 462, 462, 462, 462]),
// Field(
// name: 'c_11',
// label: 'Holding Procedures',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [476, 476, 476, 476, 476, 476]),
// Field(
// name: 'c_12',
// label: 'Precision Approach Procedure',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [490, 490, 490, 490, 490, 490]),
// Field(
// name: 'c_13_check',
// label: 'Non precision Approach Procedure ..........',
// type: FieldType.checkbox,
// listValue: [
// 'RNP-RNAV',
// 'VOR',
// 'LOC',
// ],
// checkBoxValue: [false, false, false],
// // intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: [194, 252, 285],
// posYList: [501, 501, 501]),
// Field(
// name: 'c_13_check_0',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'c_13_check_1',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'c_13_check_2',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'c_13',
// label: 'Non precision Approach Procedure',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [503, 503, 503, 503, 503, 503]),
// Field(
// name: 'c_14',
// label: 'Go Around / Missed Approach Procedure with all engines',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [517, 517, 517, 517, 517, 517]),
// Field(
// name: 'c_15',
// label:
// 'Go Around / Missed Approach Procedure with one engine failure',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [531, 531, 531, 531, 531, 531]),
// Field(
// name: 'c_16',
// label: 'Use of Auto Pilot / Flight Director',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// posXList: _gradePosX,
// posYList: [545, 545, 545, 545, 545, 545]),
// Field(
// name: 'c_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 3,
// gradeSection: 3,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 450,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'd_17',
// label: 'Steep Turns',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 4,
// gradeSection: 4,
// posXList: _gradePosX,
// posYList: [572, 572, 572, 572, 572, 572]),
// Field(
// name: 'd_18_check',
// label: 'Approaches to Stalls Recovery ..........',
// type: FieldType.checkbox,
// listValue: [
// 'Clean Configuration',
// 'Landing Configuration',
// ],
// checkBoxValue: [false, false],
// page: 1,
// section: 3,
// subSection: 4,
// gradeSection: 4,
// posXList: [179, 265],
// posYList: [584, 584]),
// Field(
// name: 'd_18_check_0',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'd_18_check_1',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'd_18',
// label: 'Approaches to Stalls Recovery',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 4,
// gradeSection: 4,
// posXList: _gradePosX,
// posYList: [586, 586, 586, 586, 586, 586]),
// Field(
// name: 'd_19',
// label: 'Specific Flight Characteristic (TCAS)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 4,
// gradeSection: 4,
// posXList: _gradePosX,
// posYList: [600, 600, 600, 600, 600, 600]),
// Field(
// name: 'd_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 4,
// gradeSection: 4,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 574,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'e_20_check',
// label: 'Approach Maneuvering ..........',
// type: FieldType.checkbox,
// listValue: [
// 'Visual Circuit',
// 'Circling Approach',
// ],
// checkBoxValue: [false, false],
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: [152, 214],
// posYList: [626, 626]),
// Field(
// name: 'e_20_check_0',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'e_20_check_1',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'e_20',
// label: 'Approach Maneuvering',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [628, 628, 628, 628, 628, 628]),
// Field(
// name: 'e_21',
// label: 'Landing with all engines',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [642, 642, 642, 642, 642, 642]),
// Field(
// name: 'e_22',
// label: 'Landing with one engine failure',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [656, 656, 656, 656, 656, 656]),
// Field(
// name: 'e_23',
// label: 'Crosswind Landing / Gusty Wind / Tailwind Landing',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [670, 670, 670, 670, 670, 670]),
// Field(
// name: 'e_24',
// label: 'Windshear during Approach',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [684, 684, 684, 684, 684, 684]),
// Field(
// name: 'e_25',
// label: 'Rejected Landing',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// posXList: _gradePosX,
// posYList: [698, 698, 698, 698, 698, 698]),
// Field(
// name: 'e_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 5,
// gradeSection: 5,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 630,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'f_26',
// label: 'Normal and Non-normal Procedure (RVSM)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 6,
// gradeSection: 6,
// posXList: _gradePosX,
// posYList: [726, 726, 726, 726, 726, 726]),
// Field(
// name: 'f_27',
// label: 'Normal and Non-normal Procedure (PBN)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 1,
// section: 3,
// subSection: 6,
// gradeSection: 6,
// posXList: _gradePosX,
// posYList: [740, 740, 740, 740, 740, 740]),
// Field(
// name: 'f_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 1,
// section: 3,
// subSection: 6,
// gradeSection: 6,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 728,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'g_28_check',
// label: 'Aircraft System Malfunction ..........',
// type: FieldType.checkbox,
// listValue: [
// 'Fuel',
// 'Electrical',
// 'Hydraulic',
// 'Auto Flight',
// 'Flight Control',
// ],
// checkBoxValue: [false, false, false, false, false],
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: [67, 98, 147, 196, 250],
// posYList: [112, 112, 112, 112, 112]),
// Field(
// name: 'g_28_check_0',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'g_28_check_1',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'g_28_check_2',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'g_28_check_3',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'g_28_check_4',
// type: FieldType.string,
// input: false,
// writePdf: false,
// stringValue: 'FALSE'),
// Field(
// name: 'g_28',
// label: 'Aircraft System Malfunction',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: _gradePosX,
// posYList: [113, 113, 113, 113, 113, 113]),
// Field(
// name: 'g_29',
// label: 'Pressurization (Rapid Decompression and Emergency Descent)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: _gradePosX,
// posYList: [127, 127, 127, 127, 127, 127]),
// Field(
// name: 'g_30',
// label: 'Fire Protection and Extinguisher',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: _gradePosX,
// posYList: [141, 141, 141, 141, 141, 141]),
// Field(
// name: 'g_31',
// label: 'Engine Failure and Restart',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: _gradePosX,
// posYList: [155, 155, 155, 155, 155, 155]),
// Field(
// name: 'g_32',
// label: 'Navigation and Avionic System',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// posXList: _gradePosX,
// posYList: [169, 169, 169, 169, 169, 169]),
// Field(
// name: 'g_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 7,
// gradeSection: 7,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 115,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'h_33',
// label: 'Engine Failure before V1 RTO',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 8,
// gradeSection: 8,
// posXList: _gradePosX,
// posYList: [197, 197, 197, 197, 197, 197]),
// Field(
// name: 'h_34',
// label: 'Engine Failure at Takeoff after V1',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 8,
// gradeSection: 8,
// posXList: _gradePosX,
// posYList: [211, 211, 211, 211, 211, 211]),
// Field(
// name: 'h_35',
// label: 'One Engine inoperative ILS Approach and Go-Around',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 8,
// gradeSection: 8,
// posXList: _gradePosX,
// posYList: [225, 225, 225, 225, 225, 225]),
// Field(
// name: 'h_36',
// label: 'One Engine inoperative ILS Approach and Landing',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 8,
// gradeSection: 8,
// posXList: _gradePosX,
// posYList: [239, 239, 239, 239, 239, 239]),
// Field(
// name: 'h_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 8,
// gradeSection: 8,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 199,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'i_37',
// label: 'Crew Resource Management (CRM)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// posXList: _gradePosX,
// posYList: [267, 267, 267, 267, 267, 267]),
// Field(
// name: 'i_38',
// label: 'Threat & Error Management',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// posXList: _gradePosX,
// posYList: [281, 281, 281, 281, 281, 281]),
// Field(
// name: 'i_39',
// label: 'Assertiveness and Interpersonal Skills',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// posXList: _gradePosX,
// posYList: [295, 295, 295, 295, 295, 295]),
// Field(
// name: 'i_40',
// label: 'Security & Safety Attitude',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// posXList: _gradePosX,
// posYList: [308, 308, 308, 308, 308, 308]),
// Field(
// name: 'i_41',
// label: 'Public Address (PA)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// posXList: _gradePosX,
// posYList: [322, 322, 322, 322, 322, 322]),
// Field(
// name: 'i_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 9,
// gradeSection: 9,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 269,
// width: 116,
// fontSize: 8),
// //---------
// Field(
// name: 'j_42',
// label: 'Flight Crew Incapacitation (If applicable)',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// posXList: _gradePosX,
// posYList: [350, 350, 350, 350, 350, 350]),
// Field(
// name: 'j_43',
// label:
// 'Emergency Procedures - including mandatory Pax Evacuation Procedures',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// posXList: _gradePosX,
// posYList: [364, 364, 364, 364, 364, 364]),
// Field(
// name: 'j_44_detail',
// label: 'Additional Exercises 1',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// textCapitalization: TextCapitalization.sentences,
// // stringValue: 'Additional 1',
// posX: 64,
// posY: 379),
// Field(
// name: 'j_44',
// label: 'Additional Exercises 1',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// posXList: _gradePosX,
// posYList: [378, 378, 378, 378, 378, 378]),
// Field(
// name: 'j_45_detail',
// label: 'Additional Exercises 2',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// textCapitalization: TextCapitalization.sentences,
// posX: 64,
// posY: 393),
// Field(
// name: 'j_45',
// label: 'Additional Exercises 2',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// posXList: _gradePosX,
// posYList: [392, 392, 392, 392, 392, 392]),
// Field(
// name: 'j_46_detail',
// label: 'Additional Exercises 3',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// mandatory: false,
// textCapitalization: TextCapitalization.sentences,
// posX: 64,
// posY: 407),
// Field(
// name: 'j_46',
// label: 'Additional Exercises 3',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// posXList: _gradePosX,
// posYList: [406, 406, 406, 406, 406, 406]),
// Field(
// name: 'j_47_detail',
// label: 'Additional Exercises 4',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// textCapitalization: TextCapitalization.sentences,
// posX: 64,
// posY: 421),
// Field(
// name: 'j_47',
// label: 'Additional Exercises 4',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// posXList: _gradePosX,
// posYList: [420, 420, 420, 420, 420, 420]),
// Field(
// name: 'j_48_detail',
// label: 'Additional Exercises 5',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// textCapitalization: TextCapitalization.sentences,
// posX: 64,
// posY: 435),
// Field(
// name: 'j_48',
// label: 'Additional Exercises 5',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// posXList: _gradePosX,
// posYList: [434, 434, 434, 434, 434, 434]),
// Field(
// name: 'j_comment',
// label: 'Comment',
// type: FieldType.string,
// page: 2,
// section: 3,
// subSection: 10,
// gradeSection: 10,
// mandatory: false,
// maxLength: gradeCommentMaxLen,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// posX: 445,
// posY: 352,
// width: 116,
// fontSize: 8),
// //---------
// ///.....................................................................
// ///Number of Manual Landing and Go-Around
// ///.....................................................................
// Field(
// name: 'no_landing',
// label: 'Number of Manual Landing',
// type: FieldType.string,
// page: 2,
// section: 4,
// subSection: 1,
// keyboardType: TextInputType.number,
// // stringValue: '0',
// posX: 230,
// posY: 460),
// Field(
// name: 'no_goaround',
// label: 'Number of Go-around',
// type: FieldType.string,
// page: 2,
// section: 4,
// subSection: 1,
// keyboardType: TextInputType.number,
// // stringValue: '0',
// posX: 492,
// posY: 460),
//
// ///.....................................................................
// ///Competency Assessment and Comments
// ///.....................................................................
// Field(
// name: 'comp_kno',
// label: 'KNO',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [518, 518, 518, 518, 518, 518]),
// Field(
// name: 'comp_pro',
// label: 'PRO',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [531, 531, 531, 531, 531, 531]),
// Field(
// name: 'comp_com',
// label: 'COM',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [545, 545, 545, 545, 545, 545]),
// Field(
// name: 'comp_fpa',
// label: 'FPA',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [559, 559, 559, 559, 559, 559]),
// Field(
// name: 'comp_fpm',
// label: 'FPM',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [572, 572, 572, 572, 572, 572]),
// Field(
// name: 'comp_ltw',
// label: 'LTW',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [586, 586, 586, 586, 586, 586]),
// Field(
// name: 'comp_psd',
// label: 'PSD',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [599, 599, 599, 599, 599, 599]),
// Field(
// name: 'comp_saw',
// label: 'SAW',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [613, 613, 613, 613, 613, 613]),
// Field(
// name: 'comp_wlm',
// label: 'WLM',
// type: FieldType.radio,
// listValue: _gradeList,
// intValue: kInitChoice,
// page: 2,
// section: 5,
// subSection: 1,
// posXList: _gradePosX,
// posYList: [627, 627, 627, 627, 627, 627]),
// Field(
// name: 'general_comment',
// label: 'General Comment',
// type: FieldType.string,
// // stringValue:
// //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
// //     ' as indicated, have supervised the required session in '
// //     'accordance with the published',
// page: 2,
// section: 5,
// subSection: 1,
// mandatory: false,
// maxLength: 500,
// posX: 42,
// posY: 520,
// width: 260,
// height: 100,
// fontSize: 8),
//
// ///.....................................................................
// ///OVERALL GRADING
// ///.....................................................................
// Field(
// name: 'result',
// label: 'Result',
// type: FieldType.radio,
// listValue: [
// '(1) Unsatisfactory',
// '(2) Improvement Required',
// '(3) Company Standard',
// '(4) Effective',
// '(5) Precise',
// ],
// intValue: kInitChoice,
// page: 2,
// section: 6,
// subSection: 1,
// posXList: [138, 228, 339, 440, 504],
// posYList: [653, 653, 653, 653, 653]),
//
// ///.....................................................................
// ///Signature
// ///.....................................................................
// Field(
// name: 'pilot_sig',
// label: 'Trainee\'s Signature',
// type: FieldType.signature,
// sigWidth: 100,
// sigMaxHeight: 60,
// page: 2,
// section: 7,
// posX: 75,
// posY: 732),
// Field(
// // name: 'PILOT_NAME',
// // label: 'Pilot Name',
// duplicateFrom: 'pilot_name',
// mandatory: false,
// input: false,
// type: FieldType.string,
// page: 2,
// section: 7,
// posX: 70,
// posY: 757),
// Field(
// name: 'pilot_sig_date',
// label: 'Date',
// // input: false,
// // mandatory: true,
// type: FieldType.date,
// keyboardType: TextInputType.datetime,
// page: 2,
// section: 7,
// stringValue:
// DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
// dateTimeValue: DateTime.now(),
// posX: 70,
// posY: 767),
// Field(
// name: 'examiner_sig',
// label: 'Examiner\'s Signature',
// type: FieldType.signature,
// sigWidth: 100,
// sigMaxHeight: 60,
// page: 2,
// section: 7,
// posX: 245,
// posY: 732),
// Field(
// // name: 'PILOT_NAME',
// // label: 'Pilot Name',
// duplicateFrom: 'examiner_name',
// mandatory: false,
// input: false,
// type: FieldType.string,
// page: 2,
// section: 7,
// posX: 245,
// posY: 757),
// Field(
// name: 'examiner_sig_date',
// label: 'Date',
// // input: false,
// // mandatory: true,
// type: FieldType.date,
// keyboardType: TextInputType.datetime,
// page: 2,
// section: 7,
// stringValue:
// DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
// dateTimeValue: DateTime.now(),
// posX: 245,
// posY: 767),
// ],
// );
// }