// // lib/services/form_definitions/line_check_form.dart
//
// import 'package:flutter/material.dart';
// import 'package:intl/intl.dart';
// import 'package:uuid/uuid.dart';
// import 'package:marverick/models/form.dart' as f;
// import 'package:marverick/models/field.dart';
// import 'package:marverick/services/authen.dart';
// import 'package:marverick/utils/constants.dart';
//
// class LineCheckForm5 {
//   static const _uuid = Uuid();
//
//   static f.Form init() {
//     DateTime timeStamp = DateTime.now();
//     List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
//     List<String> _boolList = ['YES', 'NO'];
//     List<double> _gradePosX = [307, 324, 342, 359, 377, 396];
//     List<double> _competentPosX = [165, 183, 201, 219, 237, 256];
//     int gradeCommentMaxLen = 180;
//     return f.Form(
//       type: f.FormType.lineCheck5,
//       formName: 'Line Check',
//       createDateTime: timeStamp,
//       createBy: Authen.user != null ? Authen.user.email : '',
//       id: uuid.v1(),
//       filePath: 'forms/linecheck5.pdf',
//       dbTable: kLineCheck5Table,
//       fontSize: 9,
//       sectionLabel: [
//         'Personal Detail',
//         'Check Detail',
//         'Grading',
//         'Briefing Items',
//         'Oral Test',
//         'Competency Assessment and Comments',
//         'Result',
//         'Signature',
//       ],
//       gradeSectionLabel: [
//         'PRE-FLIGHT PREPARATION AND ENGINE START',
//         'TAXI AND TAKEOFF',
//         'CLIMB AND CRUISE',
//         'DESCENT / APPROACH AND LANDING',
//         'NON-TECHNICAL',
//       ],
//       formLabel: 'Line Check',
//       formLabelInfoField1: 'pilot_rank',
//       formLabelInfoField2: 'pilot_name',
//       dateFormat: 'dd/MM/yyyy',
//       // ruler: true,
//       fields: [
//         ///.....................................................................
//         ///PILOT
//         ///.....................................................................
//         // Field(
//         //     name: 'pilot_rank',
//         //     label: 'Pilot Rank',
//         //     type: FieldType.radio,
//         //     listValue: ['Capt.', 'FO.'],
//         //     intValue: kInitChoice,
//         //     section: 1,
//         //     subSection: 1,
//         //     page: 1,
//         //     posXList: [152, 178],
//         //     posYList: [100, 100]),
//         Field(
//             name: 'pilot_name',
//             label: 'Pilot Name',
//             type: FieldType.string,
//             stringValue: 'FO. ',
//             section: 1,
//             subSection: 1,
//             // stringValue: 'Teerachart Jongkoldee',
//             posX: 149,
//             posY: 104),
//         Field(
//             name: 'pilot_license_no',
//             label: 'Pilot License No.',
//             type: FieldType.string,
//             section: 1,
//             subSection: 1,
//             // stringValue: 'TH.FCL.0001234',
//             posX: 149,
//             posY: 119),
//         Field(
//             name: 'pilot_id',
//             label: 'Pilot Staff ID No.(xxxx)',
//             type: FieldType.string,
//             section: 1,
//             subSection: 1,
//             maxLength: 4,
//             keyboardType: TextInputType.number,
//             // stringValue: '0895',
//             posX: 165,
//             posY: 134),
//
//         ///.....................................................................
//         ///EXAMINER
//         ///.....................................................................
//         // Field(
//         //     name: 'examiner_rank',
//         //     label: 'Examiner Rank',
//         //     type: FieldType.radio,
//         //     listValue: ['DCP', 'FI-A', 'SV'],
//         //     intValue: kInitChoice,
//         //     section: 1,
//         //     subSection: 2,
//         //     page: 1,
//         //     posXList: [360, 385, 410],
//         //     posYList: [100, 100, 100]),
//         Field(
//             name: 'examiner_name',
//             label: 'Examiner Name',
//             type: FieldType.string,
//             stringValue: 'CAPT. ',
//             section: 1,
//             subSection: 2,
//             posX: 357,
//             posY: 104),
//         Field(
//             name: 'examiner_license_no',
//             label: 'Examiner License / Certificate No.',
//             type: FieldType.string,
//             section: 1,
//             subSection: 2,
//             posX: 357,
//             posY: 119),
//         Field(
//             name: 'examiner_id',
//             label: 'Examiner Staff ID No.(xxxx)',
//             type: FieldType.string,
//             section: 1,
//             subSection: 2,
//             maxLength: 4,
//             keyboardType: TextInputType.number,
//             posX: 375,
//             posY: 134),
//
//         ///.....................................................................
//         ///CHECK DETAILS
//         ///.....................................................................
//         Field(
//             name: 'type_of_check',
//             label: 'Type Of Check',
//             type: FieldType.radio,
//             listValue: [
//               'Initial',
//               'Annual',
//               'Recency',
//               'Requalification',
//               'Other'
//             ],
//             intValue: kInitChoice,
//             section: 2,
//             subSection: 1,
//             page: 1,
//             posXList: [45, 45, 45, 45, 45],
//             posYList: [175, 190, 205, 221, 237]),
//         Field(
//             name: 'other_type',
//             label: 'Other(if selected)',
//             type: FieldType.string,
//             section: 2,
//             subSection: 1,
//             isMandatory: false,
//             posX: 75,
//             posY: 238),
//         Field(
//             name: 'ac_type_1',
//             label: 'Sector 1 A/C Type',
//             type: FieldType.radio,
//             listValue: ['A320', 'A321', 'B737-8'],
//             intValue: kInitChoice,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             posXList: [323, 360, 396],
//             posYList: [159, 159, 159]),
//         Field(
//             name: 'ac_reg_1',
//             label: 'Sector 1 Registration (HS-___)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             maxLength: 3,
//             minLength: 3,
//             posX: 370,
//             posY: 222),
//         Field(
//             name: 'date_1',
//             label: 'Sector 1 Date',
//             // type: FieldType.string,
//             type: FieldType.date,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             keyboardType: TextInputType.datetime,
//             stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
//             dateTimeValue: DateTime.now(),
//             posX: 352,
//             posY: 178),
//         Field(
//             name: 'flt_no_1',
//             label: 'Sector 1 Flight No. (VZ___)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             maxLength: 4,
//             keyboardType: TextInputType.number,
//             posX: 370,
//             posY: 191),
//         Field(
//             name: 'from_1',
//             label: 'Sector 1 From (ICAO)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             maxLength: 4,
//             minLength: 4,
//             stringValue: 'VTBS',
//             posX: 345,
//             posY: 207),
//         Field(
//             name: 'to_1',
//             label: 'Sector 1 To (ICAO)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             maxLength: 4,
//             minLength: 4,
//             posX: 378,
//             posY: 207),
//         Field(
//             name: 'duty_1',
//             label: 'Sector 1 Duty',
//             type: FieldType.radio,
//             listValue: ['PF', 'PM'],
//             intValue: kInitChoice,
//             page: 1,
//             section: 2,
//             subSection: 2,
//             posXList: [356, 379],
//             posYList: [236, 236]),
//         Field(
//             name: 'ac_type_2',
//             label: 'Sector 2 A/C Type',
//             type: FieldType.radio,
//             listValue: ['A320', 'A321', 'B737-8'],
//             intValue: kInitChoice,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             posXList: [446, 483, 519],
//             posYList: [159, 159, 159]),
//         Field(
//             name: 'ac_reg_2',
//             label: 'Sector 2 Registration (HS-___)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             maxLength: 3,
//             minLength: 3,
//             posX: 493,
//             posY: 222),
//         Field(
//             name: 'date_2',
//             label: 'Sector 2 Date',
//             type: FieldType.date,
//             keyboardType: TextInputType.datetime,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
//             dateTimeValue: DateTime.now(),
//             posX: 475,
//             posY: 178),
//         Field(
//             name: 'flt_no_2',
//             label: 'Sector 2 Flight No. (VZ___)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             maxLength: 4,
//             keyboardType: TextInputType.number,
//             posX: 493,
//             posY: 191),
//         Field(
//             name: 'from_2',
//             label: 'Sector 2 From (ICAO)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             maxLength: 4,
//             minLength: 4,
//             posX: 468,
//             posY: 207),
//         Field(
//             name: 'to_2',
//             label: 'Sector 2 To (ICAO)',
//             type: FieldType.string,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             maxLength: 4,
//             minLength: 4,
//             stringValue: 'VTBS',
//             posX: 501,
//             posY: 207),
//         Field(
//             name: 'duty_2',
//             label: 'Sector 2 Duty',
//             type: FieldType.radio,
//             listValue: ['PF', 'PM'],
//             intValue: kInitChoice,
//             page: 1,
//             section: 2,
//             subSection: 3,
//             posXList: [479, 502],
//             posYList: [236, 236]),
//
//         ///.....................................................................
//         ///GRADING
//         ///.....................................................................
//         Field(
//             name: 'q1',
//             label:
//             'Flight documents, Security check, Flight crew and Cabin crew briefing',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 332),
//         Field(
//             name: 'q2',
//             label: 'Fuel policy / FMGS preparation / X-check',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 344),
//         Field(
//             name: 'q3',
//             label: 'Aircraft status / MEL',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 356),
//         Field(
//             name: 'q4',
//             label: 'Aircraft safety inspection (Exterior and Internal)',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 368),
//         Field(
//             name: 'q5',
//             label: 'Load sheet / Takeoff performance calculation',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 380),
//         Field(
//             name: 'q6',
//             label: 'Takeoff briefing / TEM / NAVAIDS setting',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 392),
//         Field(
//             name: 'q7',
//             label: 'Timely Engine Start / Monitoring Engine Start',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             posXList: _gradePosX,
//             posY: 404),
//         Field(
//             name: 'a_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 1,
//             section: 3,
//             subSection: 1,
//             gradeSection: 1,
//             isMandatory: false,
//             maxLength: gradeCommentMaxLen,
//             posX: 410,
//             posY: 333,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//         Field(
//             name: 'q8',
//             label: 'ATC / Ground crew coordination',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 428),
//         Field(
//             name: 'q9',
//             label: 'Taxi technique',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 440),
//         Field(
//             name: 'q10',
//             label: 'Takeoff techique',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 452),
//         Field(
//             name: 'q11',
//             label: 'SID / ATC compliance',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 464),
//         Field(
//             name: 'q12',
//             label: 'Noise Abatement procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 476),
//         Field(
//             name: 'q13',
//             label: 'PM Support / Callouts / Procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             posXList: _gradePosX,
//             posY: 488),
//         Field(
//             name: 'b_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 1,
//             section: 3,
//             subSection: 2,
//             gradeSection: 2,
//             isMandatory: false,
//             maxLength: gradeCommentMaxLen,
//             posX: 410,
//             posY: 429,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//         Field(
//             name: 'q14',
//             label: 'Climb technique / Procedure',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             posXList: _gradePosX,
//             posY: 512),
//         Field(
//             name: 'q15',
//             label: 'Altitude selection / Step climb',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             posXList: _gradePosX,
//             posY: 524),
//         Field(
//             name: 'q16',
//             label: 'In-flight planning / Re-planning / Emergency procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             posXList: _gradePosX,
//             posY: 536),
//         Field(
//             name: 'q17',
//             label: 'Enroute Comms / ATC procedure and compliance',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             posXList: _gradePosX,
//             posY: 548),
//         Field(
//             name: 'q18',
//             label: 'CAT / Wake Turbulence / WX Avoidance procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             posXList: _gradePosX,
//             posY: 560),
//         Field(
//             name: 'c_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 1,
//             section: 3,
//             subSection: 3,
//             gradeSection: 3,
//             isMandatory: false,
//             maxLength: gradeCommentMaxLen,
//             posX: 410,
//             posY: 513,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//         Field(
//             name: 'q19',
//             label: 'Descent planning / Briefing / TEM / Situation awareness',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 584),
//         Field(
//             name: 'q20',
//             label:
//             'Profile management / Speed / Altitude / Aircraft configuration',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 596),
//         Field(
//             name: 'q21',
//             label: 'STAR / ATC compliance',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 608),
//         Field(
//             name: 'q22',
//             label: 'Approach procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 620),
//         Field(
//             name: 'q23',
//             label: 'Stabilized Approach Criteria',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 632),
//         Field(
//             name: 'q24',
//             label: 'Landing technique',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 644),
//         Field(
//             name: 'q25',
//             label:
//             'Reversers / Braking / Runway clearance (Vacating) / Runway occupancy time',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 661),
//         Field(
//             name: 'q26',
//             label: 'Parking / Shut Down procedure',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 676),
//         Field(
//             name: 'q27',
//             label: 'Post-Flight documents / Procedures',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 688),
//         Field(
//             name: 'q28',
//             label: 'PM support',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             posXList: _gradePosX,
//             posY: 700),
//         Field(
//             name: 'd_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 1,
//             section: 3,
//             subSection: 4,
//             gradeSection: 4,
//             isMandatory: false,
//             maxLength: gradeCommentMaxLen,
//             posX: 410,
//             posY: 585,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//         Field(
//             name: 'q29',
//             label: 'Crew Resource Management (CRM)',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 725),
//         Field(
//             name: 'q30',
//             label: 'Threat & Error Management (TEM)',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 737),
//         Field(
//             name: 'q31',
//             label: 'Assertiveness',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 749),
//         Field(
//             name: 'q32',
//             label: 'Interpersonal Skills',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 1,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 764),
//         Field(
//             name: 'q33',
//             label: 'Security-Safety Attitude',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 110),
//         Field(
//             name: 'q34',
//             label: 'Public Address (PA)',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             posXList: _gradePosX,
//             posY: 122),
//         Field(
//             name: 'e_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 1,
//             section: 3,
//             subSection: 5,
//             gradeSection: 5,
//             isMandatory: false,
//             maxLength: gradeCommentMaxLen,
//             posX: 410,
//             posY: 725,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//
//         ///.....................................................................
//         ///BRIEFING ITEM
//         ///.....................................................................
//         Field(
//             name: 'brief_1',
//             label: 'Hard Landing Awareness',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 201),
//         Field(
//             name: 'brief_2',
//             label: 'Un-stabilized Approach Prevention and Mitigation',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 213),
//         Field(
//             name: 'brief_3',
//             label: 'Short Flare / Long Flare Landing',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 225),
//         Field(
//             name: 'brief_4',
//             label: 'Taxi way / Runway incursion and excursion',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 237),
//         Field(
//             name: 'brief_5',
//             label: 'Taxi Speed Limitation',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 249),
//         Field(
//             name: 'brief_6',
//             label: 'Green Operations Procedure',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 4,
//             posXList: _gradePosX,
//             posY: 261),
//         Field(
//             name: 'brief_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 2,
//             section: 4,
//             isMandatory: false,
//             maxLength: 300,
//             posX: 410,
//             posY: 202,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//
//         ///.....................................................................
//         ///ORAL TEST
//         ///.....................................................................
//         Field(
//             name: 'oral_1_text',
//             label: 'Oral Test#1',
//             type: FieldType.string,
//             stringValue: Authen.isTjo() ? 'Oral no 1' : '',
//             page: 2,
//             section: 5,
//             posX: 78,
//             posY: 332),
//         Field(
//             name: 'oral_1',
//             label: 'Oral Test#1 Grading',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 5,
//             posXList: _gradePosX,
//             posY: 330),
//         Field(
//             name: 'oral_2_text',
//             label: 'Oral Test#2',
//             type: FieldType.string,
//             stringValue: Authen.isTjo() ? 'Oral no 2' : '',
//             page: 2,
//             section: 5,
//             posX: 78,
//             posY: 344),
//         Field(
//             name: 'oral_2',
//             label: 'Oral Test#2 Grading',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 5,
//             posXList: _gradePosX,
//             posY: 342),
//         Field(
//             name: 'oral_3_text',
//             label: 'Oral Test#3',
//             type: FieldType.string,
//             stringValue: Authen.isTjo() ? 'Oral no 3' : '',
//             page: 2,
//             section: 5,
//             posX: 78,
//             posY: 356),
//         Field(
//             name: 'oral_3',
//             label: 'Oral Test#3 Grading',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 5,
//             posXList: _gradePosX,
//             posY: 354),
//         Field(
//             name: 'oral_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 2,
//             section: 5,
//             isMandatory: false,
//             maxLength: 300,
//             posX: 410,
//             posY: 332,
//             width: 145,
//             height: 100,
//             fontSize: 8),
//
//         ///.....................................................................
//         ///COMPETENCY ASSESSMENT AND COMMENTS
//         ///.....................................................................
//         Field(
//             name: 'comp_pro',
//             label: 'PRO',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 434),
//         Field(
//             name: 'comp_com',
//             label: 'COM',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 446),
//         Field(
//             name: 'comp_fpa',
//             label: 'FPA',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 458),
//         Field(
//             name: 'comp_fpm',
//             label: 'FPM',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 470),
//         Field(
//             name: 'comp_kno',
//             label: 'KNO',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 482),
//         Field(
//             name: 'comp_ltw',
//             label: 'LTW',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 494),
//         Field(
//             name: 'comp_psd',
//             label: 'PSD',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 506),
//         Field(
//             name: 'comp_saw',
//             label: 'SAW',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 518),
//         Field(
//             name: 'comp_wlm',
//             label: 'WLM',
//             type: FieldType.radio,
//             listValue: _gradeList,
//             intValue: kInitChoice,
//             page: 2,
//             section: 6,
//             posXList: _competentPosX,
//             posY: 530),
//         Field(
//             name: 'general_comment',
//             label: 'General Comment',
//             type: FieldType.string,
//             page: 2,
//             section: 6,
//             isMandatory: false,
//             maxLength: 500,
//             posX: 280,
//             posY: 437,
//             width: 275,
//             height: 100,
//             fontSize: 8),
//
//         ///.....................................................................
//         ///OVERALL GRADING
//         ///.....................................................................
//         Field(
//             name: 'result',
//             label: 'Result',
//             type: FieldType.radio,
//             listValue: ['Not Competent', 'Competent'],
//             intValue: kInitChoice,
//             page: 2,
//             section: 7,
//             posXList: [145, 149],
//             posYList: [569, 607]),
//         Field(
//             name: 'competent_level',
//             label: 'Competent Level (if competent)',
//             type: FieldType.radio,
//             listValue: [
//               'Improvement Required',
//               'Average',
//               'Above Average',
//               'Good'
//             ],
//             intValue: kInitChoice,
//             page: 2,
//             section: 7,
//             posX: 214,
//             posYList: [584, 600, 615, 630]),
//         Field(
//             name: 'result_comment',
//             label: 'Comment',
//             type: FieldType.string,
//             page: 2,
//             section: 7,
//             isMandatory: false,
//             maxLength: 350,
//             posX: 327,
//             posY: 573,
//             width: 230,
//             height: 100,
//             fontSize: 8),
//
//         ///.....................................................................
//         ///SIGNATURE
//         ///.....................................................................
//         Field(
//             name: 'pilot_sig',
//             label: 'Pilot\'s Signature',
//             type: FieldType.signature,
//             sigWidth: 100,
//             sigMaxHeight: 60,
//             page: 2,
//             section: 8,
//             posX: 80,
//             posY: 715),
//         Field(
//             duplicateFrom: 'pilot_name',
//             isMandatory: false,
//             input: false,
//             type: FieldType.string,
//             page: 2,
//             section: 8,
//             posX: 70,
//             posY: 735),
//         Field(
//             name: 'pilot_sig_date',
//             label: 'Date',
//             // input: false,
//             // mandatory: true,
//             type: FieldType.date,
//             keyboardType: TextInputType.datetime,
//             page: 2,
//             section: 8,
//             stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
//             dateTimeValue: DateTime.now(),
//             posX: 70,
//             posY: 751),
//         //
//         ///++++++++++++++++++++++++++++++++++++++++++++++++
//         Field(
//             name: 'examiner_sig',
//             label: 'Examiner\'s Signature',
//             type: FieldType.signature,
//             sigWidth: 100,
//             sigMaxHeight: 60,
//             page: 2,
//             section: 8,
//             posX: 250,
//             posY: 715),
//         Field(
//             duplicateFrom: 'examiner_name',
//             input: false,
//             isMandatory: false,
//             type: FieldType.string,
//             page: 2,
//             section: 8,
//             posX: 250,
//             posY: 735),
//         Field(
//             name: 'examiner_sig_date',
//             label: 'Date',
//             // input: false,
//             type: FieldType.date,
//             keyboardType: TextInputType.datetime,
//             dateTimeValue: DateTime.now(),
//             // mandatory: false,
//             page: 2,
//             section: 8,
//             stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
//             posX: 250,
//             posY: 751),
//       ],
//     );
//   }
// }
