// lib/services/form_definitions/line_check_form.dart

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';

import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class LineCheckForm {
  static const uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;

    String formName = 'forms/rt32.pdf';
    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training as indicated, have supervised the required session in accordance with the published';
    // int defaultGrade() => Authen.isTjo() ? -1 : -1;
    // bool defaultCheck = true;

    return f.Form(
      type: f.FormType.rt3,
      formName: 'RT3',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName,
      dbTable: kRt3Table,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'DISCUSSION - PERFORMANCE',
        'PREFLIGHT PREPARATION AND GROUND OPERATIONS',
        'TAKEOFF',
        'INFLIGHT MANEUVERS AND PROCEDURES',
        'AIRCRAFT SYSTEM MALFUNCTION',
        'ABNORMAL AND EMERGENCY PROCEDURE',
        'MISSED APPROACH PROCEDURES',
        'LANDINGS AND AFTER LANDING PROCEDURES',
        'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
        'NON-TECHNICAL',
        'EGPWS',
      ],
      formLabel: 'RT3',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [132, 219, 219],
            posYList: [84, 84, 84]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 106),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s FCL No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 365,
            posY: 88),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 386,
            posY: 105),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'SFI\'s Rank',
            type: FieldType.radio,
            listValue: ['CAPT'],
            stringValue: 'CAPT',
            intValue: 0,
            editable: false,
            section: 1,
            subSection: 2,
            posXList: [132],
            posYList: [117]),
        Field(
            name: 'instructor_name',
            label: 'SFI\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 140),
        Field(
            name: 'instructor_cert_no',
            label: 'FIC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 368,
            posY: 122),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 386,
            posY: 139),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 493,
            posY: 88),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
            // stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            posX: 493,
            posY: 105),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 493,
            posY: 122),
        Field(
            name: 'ac_type',
            label: 'ACFT Type',
            type: FieldType.radio,
            listValue: ['A320', 'B737'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 527],
            posYList: [135, 135]),
        Field(
            name: 'route',
            label: 'Route (ICAO AIRPORT CODE e.g. VTBS-VTCC)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'VTBS-RCTP' : '',
            section: 2,
            posX: 368,
            posY: 158),
        Field(
            name: 'rhs',
            label: 'RHS',
            type: FieldType.radio,
            listValue: ['Yes', 'No'],
            intValue: Authen.isTjo() ? 0 : -1,
            section: 2,
            posXList: [219, 1000],
            posYList: [153, 1000]),
        Field(
            name: 'loft_duty',
            label: 'LOFT Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 520],
            posYList: [153, 153]),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label:
                'Adverse Weather / Runway Contamination / Thunderstorm Avoidance*',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 225),
        Field(
            name: 'q2',
            label: 'Drift Down Procedure and Diversion Strategy*',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 238),
        Field(
            name: 'q3',
            label: 'RVSM and China RVSM Procedures*',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 252),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 225,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q4',
            label: 'Preflight Preparation / Briefing / TEM / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 279),
        Field(
            name: 'q5_detail',
            label: 'Abnormal Engine Start …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: Authen.isTjo() ? 'HOT START' : '',
            posX: 200,
            posY: 293),
        Field(
            name: 'q5',
            label:
                'Engine Start / Abnormal Engine Start …………………………. / After Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 293),
        Field(
            name: 'q6',
            label:
                'Taxi Technique / Assistance / ATC Compliance / Before Takeoff Check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 306),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 280,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q7',
            label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 334),
        Field(
            name: 'q8',
            label: 'Cross Wind Takeoff / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 347),
        Field(
            name: 'q9',
            label: 'Rejected Takeoff at a reasonable speed before reaching V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 361),
        Field(
            name: 'q10',
            label: 'Takeoff with Simulated Engine Failure / Fire at V2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 375),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 335,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q11',
            label: 'SID - Standard Instrument Departure / RNAV SID',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 402),
        Field(
            name: 'q12',
            label:
                'STAR - Standard Terminal Arrival Route / RNAV STAR / Holding Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 416),
        Field(
            name: 'q13',
            label: '3D Approach to DH/A of 200 Feet or Higher',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 430),
        Field(
            name: 'q14_check',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.checkbox,
            listValue: ['RNP-RNAV', 'VOR', 'LOC'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [119, 177, 212],
            posY: 443),
        Field(
            name: 'q14_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 445),
        Field(
            name: 'q15',
            label: 'Manual Fly with / without Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 459),
        Field(
            name: 'q16',
            label: 'Manual Fly with One Engine Inoperative',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 473),
        Field(
            name: 'q17_check',
            label: 'Approach Maneuvering .........',
            type: FieldType.checkbox,
            listValue: ['Visual Circuit', ' Circling Approach'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [155, 219],
            posY: 485),
        Field(
            name: 'q17_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q17_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q17',
            label: 'Approach Maneuvering',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 487),
        Field(
            name: 'q18',
            label:
                'PBN Operations (*): Normal and Non-normal Procedure (Loss of RNP)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 501),
        Field(
            name: 'q19',
            label: 'IR: Instrument Departure / Arrival / Approach',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 515),
        Field(
            name: 'q20',
            label:
                'Automation Policy Adherence: Use the Appropriate Level of Automation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 529),
        Field(
            name: 'q21',
            label: 'Weather Avoidance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 543),
        Field(
            name: 'q22',
            label: 'Approach Preparation / Briefing / TEM / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 556),
        Field(
            name: 'q23',
            label: 'Descent and Approach Management / Aircraft Configuration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 570),
        Field(
            name: 'q24',
            label: 'Stabilized Approach Criteria and Compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 583),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 403,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q25_check',
            label: 'Auto Flight',
            type: FieldType.checkbox,
            listValue: [
              'A/P Inop',
              'A/THR Inop',
              'FAC Fault',
              'FCU or MCP Fault',
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [111, 158, 217, 270],
            posY: 609),
        Field(
            name: 'q25_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25_check_3',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25',
            label: 'Auto Flight',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 612),
        Field(
            name: 'q26_check',
            label: 'Oxygen',
            type: FieldType.checkbox,
            listValue: ['Flight Crew Oxygen', 'Passenger Oxygen'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [100, 187],
            posY: 624),
        Field(
            name: 'q26_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q26_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q26',
            label: 'Oxygen',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 626),
        Field(
            name: 'q27_check',
            label: 'APU',
            type: FieldType.checkbox,
            listValue: [
              'Fault-Auto Shut Down',
              'Low Oil Press',
              'Overspeed',
              'APU Fire'
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [89, 184, 250, 306],
            posY: 639),
        Field(
            name: 'q27_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q27_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q27_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q27_check_3',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q27',
            label: 'APU',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 641),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 612,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q28',
            label: 'Engine Fire and Decision Making',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 670),
        Field(
            name: 'q29',
            label: 'Engine Failures / Shutdown / Restart',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 683),
        Field(
            name: 'q30',
            label:
                'Engine Failure in Cruise Drift Down Procedures and Diversion Strategy',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 697),
        Field(
            name: 'q31',
            label: 'Windshear at Takeoff / Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 711),
        Field(
            name: 'q32',
            label: 'TCAS TA Response (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 724),
        Field(
            name: 'q33',
            label: 'TCAS RAs - Maintain rate RAs / Weakening RAs (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 738),
        Field(
            name: 'q34_check',
            label: 'Approaches to Stalls Recovery.........',
            type: FieldType.checkbox,
            listValue: ['Clean', 'Landing Configuration'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: [179, 216],
            posY: 750),
        Field(
            name: 'q34_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            stringValue: 'FALSE'),
        Field(
            name: 'q34_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            stringValue: 'FALSE'),
        Field(
            name: 'q34',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 754),
        Field(
            name: 'q35',
            label: 'Pilot Incapacitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 767),
        Field(
            name: 'q36',
            label: 'Declaration of Emergency or Urgency',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 781),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 670,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q37',
            label: 'Go Around / Missed Approach Procedure with all engines',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 111),
        Field(
            name: 'q38',
            label:
                'Go Around / Missed Approach Procedure with one engine failure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 125),
        Field(
            name: 'q39',
            label: 'Rejected Landing below DH / MDH / After Touchdown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 138),
        Field(
            name: 'q40',
            label: 'Go Around from Intermediate Altitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 151),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 110,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q41',
            label: 'Normal Landing / Landing Technique / Landing Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 179),
        Field(
            name: 'q42',
            label: 'Landing in Out-Of-Trim Position',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 192),
        Field(
            name: 'q43',
            label: 'Crosswind landings / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 206),
        Field(
            name: 'q44',
            label: 'Reduced Flaps Landing (Flap3 or less)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 220),
        Field(
            name: 'q45',
            label: 'Landing with Simulated Engine Failure (Critical Engine)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 234),
        Field(
            name: 'q46',
            label:
                'Landing Roll / After Landing / Parking / Securing Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 248),
        Field(
            name: 'q47',
            label: 'Pax Evacuation Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 262),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 180,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q48',
            label: 'Engine Failure before V1 RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 289),
        Field(
            name: 'q49',
            label: 'Engine Failure at Takeoff after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 303),
        Field(
            name: 'q50',
            label: 'One Engine ILS Approach Go-Around and Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 317),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 290,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q51',
            label:
                'Crew Resource Management (CRM) / Assertiveness / Support Process',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 344),
        Field(
            name: 'q52',
            label: 'Threat & Error Management / Security & Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 358),
        Field(
            name: 'q53',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 372),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 344,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q54',
            label: 'EGPWS Mode 1: Excessive Sink Rate',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 399),
        Field(
            name: 'q55',
            label: 'EGPWS Mode 2: Excessive Terrain Closure Rate',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 413),
        Field(
            name: 'q56',
            label: 'EGPWS Mode 3: Descent After Takeoff or Go-Around',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 426),
        Field(
            name: 'qk_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 399,
            width: 115,
            fontSize: 8),

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 447),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 447),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 493),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 506),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 519),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 532),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 543),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 556),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 569),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 582),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 595),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 5,
            subSection: 1,
// isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 495,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [138, 226, 339, 441, 505],
            posY: 623),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 75,
            posY: 712),
        Field(
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 738),
        Field(
// name: 'pilot_sig_date',
// label: 'Date',
            type: FieldType.date,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
// keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
// stringValue:
//     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
// dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 748),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 245,
            posY: 712),
        Field(
            duplicateFrom: 'instructor_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 245,
            posY: 738),
        Field(
// name: 'instructor_sig_date',
// label: 'Date',
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
// keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
// stringValue:
//     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 245,
            posY: 748),
      ],
    );
  }
}
