// lib/services/form_definitions/line_check_form.dart

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';

import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class LineCheckForm {
  static const uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;
    String formName = 'forms/stdloft.pdf';
    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training as indicated, have supervised the required session in accordance with the published';
// int defaultGrade() => Authen.isTjo() ? -1 : -1;
// bool defaultCheck = true;

    return f.Form(
      type: f.FormType.stdloft,
      formName: 'STDLOFT',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName,
      dbTable: kStdloftTable,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PREFLIGHT PREPARATION AND GROUND OPERATIONS',
        'TAKEOFF',
        'INFLIGHT MANEUVERS AND PROCEDURES',
        'AIRCRAFT SYSTEM MALFUNCTION',
        'ABNORMAL AND EMERGENCY PROCEDURE',
        'MISSED APPROACH PROCEDURES',
        'LANDINGS AND AFTER LANDING PROCEDURES',
        'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
        'NON-TECHNICAL',
        'OPS SPEC / ADDITIONAL EXERCISES / OTHERS',
      ],
      formLabel: 'STANDARD LOFT',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      // ruler: true,
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [132, 219, 219],
            posYList: [84, 84, 84]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 106),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s FCL No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 365,
            posY: 88),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 386,
            posY: 105),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'Instructor\'s Rank',
            type: FieldType.radio,
            listValue: ['SFI', 'FI-S'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 2,
            posXList: [132, 219],
            posYList: [117, 117]),
        Field(
            name: 'instructor_name',
            label: 'Instructor\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 140),
        Field(
            name: 'instructor_cert_no',
            label: 'FIC / IC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 368,
            posY: 122),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 386,
            posY: 139),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
// type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 493,
            posY: 88),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
// stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            posX: 493,
            posY: 105),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 493,
            posY: 122),
        Field(
            name: 'ac_type',
            label: 'ACFT Type',
            type: FieldType.radio,
            listValue: ['A320', 'B737'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 527],
            posYList: [135, 135]),
        Field(
            name: 'route',
            label: 'Route (DEP-DES)',
            type: FieldType.string,
            section: 2,
            posX: 368,
            posY: 158),
        Field(
            name: 'loft_duty',
            label: 'LOFT Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 523],
            posYList: [153, 153]),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label:
                'Knowledge (General / Perf. / Planning / OPS Pros. / Other related items)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 221),
        Field(
            name: 'q2',
            label:
                'Preflight Preparation / Cockpit inspection / TEM & Briefings / Use of Checklist (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 234),
        Field(
            name: 'q3_detail',
            label: 'Abnormal Engine Start …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            stringValue: Authen.isTjo() ? 'HOT START' : '',
            posX: 205,
            posY: 248),
        Field(
            name: 'q3',
            label:
                'Engine Start / Abnormal Engine Start ………………………. / After Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 248),
        Field(
            name: 'q4',
            label:
                'Taxiing in Compliance with ATC Instructions / Before Takeoff Check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 262),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 222,
            width: 115,
            fontSize: 8),
//
        ///------------------------------------
        Field(
            name: 'q5',
            label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 290),
        Field(
            name: 'q6',
            label: 'Gusty Wind / Cross Wind Takeoff',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 303),
        Field(
            name: 'q7',
            label: 'Rejected Takeoff at a reasonable speed before reaching V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 317),
        Field(
            name: 'q8',
            label: 'Takeoff with Simulated Engine Failure at V2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 330),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 289,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q9',
            label: 'Enroute Procedures, Weather Avoidance, Inflight Planning',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 358),
        Field(
            name: 'q10',
            label: 'SID - Standard Instrument Departure / RNAV SID',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 372),
        Field(
            name: 'q11',
            label:
                'STAR Standard Terminal Arrival Route / RNAV STAR / Holding Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 385),
        Field(
            name: 'q12_check',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.checkbox,
            listValue: ['Clean', 'Landing Configuration'],
            checkBoxValue: [defaultCheck, defaultCheck],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [179, 217],
            posY: 398),
        Field(
            name: 'q12_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q12_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q12',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 400),
        Field(
            name: 'q13',
            label: '3D Approach to DH/A of 200 feet or higher minima',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 414),
        Field(
            name: 'q14_check',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.checkbox,
            listValue: ['RNP-RNAV', 'VOR', 'LOC'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [119, 177, 212],
            posY: 427),
        Field(
            name: 'q14_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q14',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 429),
        Field(
            name: 'q15',
            label: 'Manual Fly with / without Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 443),
        Field(
            name: 'q16',
            label: 'Manual Fly with One Engine Inoperative',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 456),
        Field(
            name: 'q17_check',
            label: 'Approach Maneuvering .........',
            type: FieldType.checkbox,
            listValue: ['Visual Circuit', ' Circling Approach'],
            checkBoxValue: [defaultCheck, defaultCheck],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [152, 216],
            posY: 470),
        Field(
            name: 'q17_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q17_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q17',
            label: 'Approach Maneuvering',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 471),
        Field(
            name: 'q18',
            label: 'PBN Operations: Normal and Non-normal Procedure (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 485),
        Field(
            name: 'q19',
            label: 'IR: Instrument Departure / Arrival / Approach (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 499),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 357,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q20',
            label: 'Pressurization / Air Condition / Bleed',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 527),
        Field(
            name: 'q21',
            label: 'Pitot / Static',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 541),
        Field(
            name: 'q22',
            label: 'Fuel',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 555),
        Field(
            name: 'q23',
            label: 'Electrical',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 569),
        Field(
            name: 'q24',
            label: 'Hydraulic',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 582),
        Field(
            name: 'q25',
            label: 'Flight Control and Trim (Degradation of Flight Control)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 596),
        Field(
            name: 'q26',
            label: 'Anti-Icing / De-Icing system / Glare Shield Heating',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 610),
        Field(
            name: 'q27',
            label: 'Autopilot / Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 623),
        Field(
            name: 'q28',
            label: 'Radios / Navigation Equipment / Instruments / FMS',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 637),
        Field(
            name: 'q29',
            label: 'Landing Gear and Brakes',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 651),
        Field(
            name: 'q30',
            label: 'Slats and Flaps',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 665),
        Field(
            name: 'q31',
            label: 'Engine / APU',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 678),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 526,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q32',
            label: 'Fire Drills',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 705),
        Field(
            name: 'q33',
            label: 'Smoke Control and Removal',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 719),
        Field(
            name: 'q34',
            label: 'Engine Failures / Shutdown / Restart',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 733),
        Field(
            name: 'q35',
            label: 'Windshear at Takeoff / Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 746),
        Field(
            name: 'q36',
            label: 'Emergency Descent / Rapid Depressurization',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 760),
        Field(
            name: 'q37',
            label: 'Pilot Incapacitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 773),
        Field(
            name: 'q38',
            label: 'TCAS event (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 787),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 704,
            width: 115),

        ///------------------------------------
        Field(
            name: 'q39',
            label: 'Go Around / Missed Approach Procedure with all engines',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 111),
        Field(
            name: 'q40',
            label:
                'Go Around / Missed Approach Procedure with one engine failure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 125),
        Field(
            name: 'q41',
            label: 'Rejected Landing below DH / MDH / After Touchdown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 138),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 110,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q42',
            label: 'Normal Landing (Obtain Visual at DA/H)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 165),
        Field(
            name: 'q43',
            label: 'Landing in Out-Of-Trim Position',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 179),
        Field(
            name: 'q44',
            label: 'Crosswind landings / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 192),
        Field(
            name: 'q45',
            label:
                'Reduced Flaps Landing (A320: Flap3 or less, B737: Flap15 or less)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 206),
        Field(
            name: 'q46',
            label: 'Landing with Simulated Engine Failure (Critical Engine)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 220),
        Field(
            name: 'q47',
            label:
                'Landing Roll / After Landing / Parking / Securing Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 234),
        Field(
            name: 'q48',
            label: 'Pax Evacuation Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 248),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
// isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 164,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q49',
            label: 'Engine Failure before V1 RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 275),
        Field(
            name: 'q50',
            label: 'Engine Failure at Takeoff after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 289),
        Field(
            name: 'q51',
            label: 'One Engine ILS Approach Go-Around and Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 303),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 276,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q52',
            label:
                'Crew Resource Management (CRM) / Assertiveness / Support Process',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 330),
        Field(
            name: 'q53',
            label: 'Threat & Error Management / Security & Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 344),
        Field(
            name: 'q54',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 358),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 329,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q55',
            label: 'RVSM Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 385),
        Field(
            name: 'q56',
            label: 'EFB Operations (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 399),
        Field(
            name: 'q57',
            label: 'EDTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 413),
        Field(
            name: 'q58',
            label: 'Use Appropriate Level of Automation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 426),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 384,
            width: 115,
            fontSize: 8),

        ///------------------------------------

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 475),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 475),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 522),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 535),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 547),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 560),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 572),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 585),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 598),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 611),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 624),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 5,
            subSection: 1,
// isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 523,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [138, 226, 339, 441, 505],
            posY: 653),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 75,
            posY: 744),
        Field(
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 770),
        Field(
            type: FieldType.date,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            page: 2,
            section: 7,
            posX: 70,
            posY: 783),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 245,
            posY: 744),
        Field(
            duplicateFrom: 'instructor_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 245,
            posY: 770),
        Field(
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            page: 2,
            section: 7,
            dateTimeValue: DateTime.now(),
            posX: 245,
            posY: 783),
// Field(
//     name: 'staff_name',
//     isMandatory: false,
//     input: false,
//     type: FieldType.string,
//     page: 2,
//     section: 7,
//     stringValue: 'JATUPATRA SUETRONG',
//     posX: 420,
//     posY: 754),
// Field(
//     name: 'staff_sig_date',
//     duplicateFrom: 'check_date',
//     label: 'Date',
//     type: FieldType.date,
//     keyboardType: TextInputType.datetime,
//     input: false,
//     page: 2,
//     section: 7,
//     stringValue:
//         DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
//     dateTimeValue: DateTime.now(),
//     posX: 420,
//     posY: 764),
      ],
    );
  }
}
