import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class CccForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<double> _gradePosX = [323, 339, 354, 370, 385, 400];
    int gradeCommentMaxLen = 250;
    int defaultGrade() => Authen.isTjo() ? 1 : -1;
    bool defaultCheck = false;

    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
    //     ' as indicated, have supervised the required session in '
    //     'accordance with the published';

    return f.Form(
      type: f.FormType.ccc,
      formName: 'CABIN CREW LINE TRAIN / CHECK',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: 'forms/ccc.pdf',
      dbTable: kCccTable,
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Flight Detail',
        'Grading',
        'Additional Comment',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PREFLIGHT BRIEFING',
        'PRE-DEPARTURE DUTIES',
        'BEFORE TAKEOFF ',
        'CRUISING',
        'APPROACH AND LANDING',
        'AFTER LANDING',
        'FLIGHT DECK PROCEDURE',
      ],
      formLabel: 'CCC',
      formLabelInfoField1: 'trainee_id',
      formLabelInfoField2: 'trainee_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'trainee_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 115,
            posY: 102),
        Field(
            name: 'trainee_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 134,
            posY: 115),

        ///.....................................................................
        ///PURSER
        ///.....................................................................
        Field(
            name: 'purser_name',
            label: 'Purser\'s Name (Familiarization ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 265,
            posY: 102),
        Field(
            name: 'purser_id',
            label: 'Purser\'s Staff No(xxxx) (Familiarization ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            isMandatory: false,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 283,
            posY: 115),

        ///.....................................................................
        ///EVALUATOR
        ///.....................................................................
        Field(
            name: 'evaluator_name',
            label: 'Evaluator\'s Name (Checking ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 3,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 416,
            posY: 102),
        Field(
            name: 'evaluator_id',
            label: 'Evaluator\'s Staff No(xxxx) (Checking ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 3,
            maxLength: 4,
            isMandatory: false,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 433,
            posY: 115),

        ///.....................................................................
        ///FLIGHT DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 116,
            posY: 129),
        Field(
            name: 'check_course',
            label: 'Training Course',
            type: FieldType.radio,
            listValue: [
              'Initial Training ',
              'Conversion Training',
              'Requalification Training',
              'Other',
            ],
            intValue: defaultGrade(),
            section: 2,
            posX: 45,
            posYList: [167, 181, 195, 208]),
        Field(
            name: 'other_course',
            label: 'Other(if selected)',
            type: FieldType.string,
            section: 2,
            isMandatory: false,
            maxLength: 30,
            posX: 75,
            posY: 210),
        //---------------------------------------
        Field(
            name: 'check_type',
            label: 'TYPE OF TRAINING / CHECKING',
            type: FieldType.radio,
            listValue: [
              'Line Familiarization',
              'Line Checking',
            ],
            intValue: defaultGrade(),
            section: 2,
            subSection: 2,
            posX: 194,
            posYList: [167, 181]),
        //---------------------------------------
        Field(
            name: 'position',
            label: 'ASSIGNED POSITION',
            type: FieldType.radio,
            listValue: [
              'P2',
              'P3',
              'P4',
              'P5',
            ],
            intValue: defaultGrade(),
            section: 2,
            subSection: 3,
            posXList: [202, 237, 271, 306],
            posY: 208),
        //---------------------------------------
        Field(
            name: 'ac_type',
            label: 'A/C Type',
            type: FieldType.radio,
            listValue: [
              'A320',
              'A321',
              'B737',
            ],
            intValue: defaultGrade(),
            section: 2,
            subSection: 4,
            posXList: [425, 473, 522],
            posY: 167),
        Field(
            name: 'ac_reg',
            label: 'A/C Registration',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            stringValue: 'VK',
            posX: 430,
            posY: 212),
        Field(
            name: 'flight',
            label: 'Flight No.',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            posX: 415,
            posY: 185),
        Field(
            name: 'route',
            label: 'Route (DEP-DES)',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            posX: 415,
            posY: 199),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label: 'On time report',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 261),
        Field(
            name: 'q2',
            label: 'Grooming',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 273),
        Field(
            name: 'q3',
            label:
                'Checking of flight documents, equipment with uniform and spare items',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 284),
        Field(
            name: 'q4',
            label: 'Flight information preparation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 296),
        Field(
            name: 'q5',
            label:
                'Update for the latest MTC / SN / CIR / CCSB / Safety bulletin',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 308),
        Field(
            name: 'q6',
            label: 'SEP, FA, and Security knowledge',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 320),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 263,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q7',
            label: 'Preflight check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 343),
        Field(
            name: 'q8',
            label: 'Report of preflight check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 355),
        Field(
            name: 'q9',
            label: 'Cabin / lavatory preparation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 367),
        Field(
            name: 'q10',
            label: 'Cabin readiness reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 378),
        Field(
            name: 'q11',
            label: 'Boarding procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 390),
        Field(
            name: 'q12',
            label: 'Head counting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 402),
        Field(
            name: 'q13',
            label: 'Exit row safety briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 413),
        Field(
            name: 'q14',
            label: 'Special pax handling',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 425),
        Field(
            name: 'q15',
            label: 'Door closing procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 437),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 345,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q16',
            label: 'Arming procedure and reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 460),
        Field(
            name: 'q17',
            label: 'Safety demonstration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 472),
        Field(
            name: 'q18',
            label: 'Cabin preparation for takeoff',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 483),
        Field(
            name: 'q19',
            label: 'Report cabin readiness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 495),
        Field(
            name: 'q20',
            label: 'Correct BRACE position at takeoff station',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 506),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 462,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q21',
            label: 'Inflight service duties',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 530),
        Field(
            name: 'q22',
            label: 'Cabin surveillance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 542),
        Field(
            name: 'q23',
            label: 'Flight deck check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 554),
        Field(
            name: 'q24',
            label: 'Turbulence procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 565),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 532,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q25',
            label: 'Stock & Amenities checking',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 589),
        Field(
            name: 'q26',
            label: 'Cabin preparation for landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 601),
        Field(
            name: 'q27',
            label: 'Final cabin checking',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 612),
        Field(
            name: 'q28',
            label: 'Report cabin readiness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 624),
        Field(
            name: 'q29',
            label: 'Correct BRACE position at landing station',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 635),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 591,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q30',
            label: 'Disarming procedure and reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 659),
        Field(
            name: 'q31',
            label: 'Door opening procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 671),
        Field(
            name: 'q32',
            label: 'Pax disembarkation and farewell',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 683),
        Field(
            name: 'q33',
            label: 'Special pax handling',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 694),
        Field(
            name: 'q34',
            label:
                'Ensure all safety equipment is available & return to its original position',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 705),
        Field(
            name: 'q35',
            label: 'Security checking and reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 717),
        Field(
            name: 'q36',
            label: 'Transit duties',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 729),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 661,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q37',
            label: 'Flight deck entry procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 753),
        Field(
            name: 'q38',
            label: 'Flight deck exit procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 764),
        Field(
            name: 'q39',
            label: 'Observer seat operation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 776),
        Field(
            name: 'q40',
            label: 'Cockpit drinks & meals',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 788),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 755,
            width: 140,
            fontSize: 8),

        ///.....................................................................
        ///ADDITIONAL COMMENT
        ///.....................................................................
        Field(
            name: 'additional_comment',
            label: 'Additional Comment (if applicable)',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 4,
            subSection: 1,
            // isMandatory: false,
            maxLength: 2000,
            posX: 42,
            posY: 100,
            width: 500,
            height: 500,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: [138, 228, 339, 440, 504],
            posY: 453),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'trainee_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 6,
            posX: 75,
            posY: 570),
        Field(
            duplicateFrom: 'trainee_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            posX: 70,
            posY: 591),
        Field(
            name: 'trainee_sig_date',
            label: 'Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 607),

        ///------------------------------------
        Field(
            name: 'purser_sig',
            label: 'Purser\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 6,
            subSection: 2,
            posX: 205,
            posY: 570),
        Field(
            duplicateFrom: 'purser_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            posX: 200,
            posY: 591),
        Field(
            name: 'purser_sig_date',
            label: 'Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            subSection: 2,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 200,
            posY: 607),

        ///------------------------------------
        Field(
            name: 'evaluator_sig',
            label: 'Evaluator\'s Signature (Only for check flight)',
            type: FieldType.signature,
            isMandatory: false,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 6,
            subSection: 3,
            posX: 335,
            posY: 570),
        Field(
            duplicateFrom: 'evaluator_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            posX: 330,
            posY: 591),
        Field(
            name: 'evaluator_result',
            label: 'Result',
            type: FieldType.radio,
            isMandatory: false,
            listValue: ['PASS', 'FAIL'],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 3,
            posXList: [321, 383],
            posY: 513),
        Field(
            name: 'evaluator_sig_date',
            label: 'Date (Only for check flight)',
            isMandatory: false,
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            subSection: 3,
            stringValue: '                  ',
            // DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 330,
            posY: 607),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Trainee info.
        'trainee_name': form.getStrVal('trainee_name'),
        'trainee_id': form.getStrVal('trainee_id'),

        ///Purser info.
        'purser_name': form.getStrVal('purser_name'),
        'purser_id': form.getStrVal('purser_id'),

        ///Evaluator
        'evaluator_name': form.getStrVal('evaluator_name'),
        'evaluator_id': form.getStrVal('evaluator_id'),

        ///Flight details
        'check_date': form.getStrVal('check_date'),
        'check_course': form.getStrVal('check_course'),
        'other_course': form.getStrVal('other_course'),
        'check_type': form.getStrVal('check_type'),
        'position': form.getStrVal('position'),
        'ac_type': form.getStrVal('ac_type'),
        'ac_reg': form.getStrVal('ac_reg'),
        'flight': form.getStrVal('flight'),
        'route': form.getStrVal('route'),

        ///Grading & Comment
        ///A
        'q1': form.getStrVal('q1s'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25': form.getStrVal('q25'),
        'q26': form.getStrVal('q26'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37': form.getStrVal('q37'),
        'q38': form.getStrVal('q38'),
        'q39': form.getStrVal('q39'),
        'q40': form.getStrVal('q40'),

        ///GRADING COMMENTS
        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qf_comment': form.getStrVal('qf_comment'),
        'qg_comment': form.getStrVal('qg_comment'),

        ///Additional Comment
        'additional_comment': form.getStrVal('additional_comment'),

        ///RESULT
        'result': form.getStrVal('result'),
        'evaluator_result': form.getStrVal('evaluator_result'),
        'trainee_sig_date': form.getStrVal('trainee_sig_date'),
        'purser_sig_date': form.getStrVal('purser_sig_date'),
        'evaluator_sig_date': form.getStrVal('evaluator_sig_date'),
      };
  }
}
