import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class DiffForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<double> _gradePosX = [362, 375, 389, 403, 417, 433];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;

    String formName = 'forms/diff.pdf';
    String defaultComment = '';

    return f.Form(
      type: f.FormType.diff,
      formName: 'DIFF',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName,
      dbTable: kDiffTable,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PREFLIGHT PREPARATION',
        'TAKEOFF AND CLIMB',
        'CRUISE / INFLIGHT MANEUVERS AND PROCEDURES',
        'DESCENT, APPROACH AND LANDING',
        'MISSED APPROACH PROCEDURES',
      ],
      formLabel: 'DIFF',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [133, 220, 220],
            posY: 79),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 100),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s FCL No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 365,
            posY: 83),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 386,
            posY: 99),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'SFI\'s Rank',
            type: FieldType.radio,
            listValue: ['SFI'],
            stringValue: 'SFI',
            intValue: 0,
            editable: false,
            section: 1,
            subSection: 2,
            posXList: [133],
            posY: 113),
        Field(
            name: 'instructor_name',
            label: 'SFI\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 134),
        Field(
            name: 'instructor_cert_no',
            label: 'FIC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 368,
            posY: 116),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 386,
            posY: 133),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 493,
            posY: 82),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
            stringValue: '04:00',
            posX: 493,
            posY: 100),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 493,
            posY: 117),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label: 'B737MAX System Knowledge and Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 198),
        Field(
            name: 'q2',
            label: 'Preflight Preparation / Before Takeoff Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 212),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 197,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q3',
            label:
                'Takeoff Procedure: Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 239),
        Field(
            name: 'q4',
            label: 'Climb Procedure: Manually flown to 10,000 ft.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 253),
        Field(
            name: 'q5',
            label: 'High AOA malfunction: Airspeed Unreliable',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 267),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 238,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q6',
            label: 'Recovery from full stall in clean configuration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 294),
        Field(
            name: 'q7',
            label: 'Runaway stabilizer non-normal procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 308),
        Field(
            name: 'q8',
            label:
                'Use of manual stabilizer trim (effective crew communication and coordination)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 321),
        Field(
            name: 'q9',
            label: 'Trimming technique: PM or PF trimming with one hand.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 335),
        Field(
            name: 'q10',
            label: 'Trimming technique: PM trimming with both hands.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 349),
        Field(
            name: 'q11',
            label:
                'Trimming technique: PM and PF both trimming with one hand.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 362),
        Field(
            name: 'q12',
            label:
                'Trimming technique: PM trimming with one hand on each handle.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 376),
        Field(
            name: 'q13',
            label:
                'Demonstrate manual trimming throughout the airspeed range.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 390),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 293,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q14',
            label: 'Non-normal procedures: Use of manual stabilizer trim',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 417),
        Field(
            name: 'q15',
            label: 'Non-normal procedures: Airspeed Unreliable',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 431),
        Field(
            name: 'q16',
            label: 'Manually flown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 445),
        Field(
            name: 'q17',
            label: 'Manually flown, ILS approach or visual approach',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 458),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 416,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q18',
            label: 'Go around and missed approach procedures.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 486),
        Field(
            name: 'q19',
            label: 'Non-normal procedures: Use of manual stabilizer trim',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 499),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 485,
            width: 140,
            fontSize: 8),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 547),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 560),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 573),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 585),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 598),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 611),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 624),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 636),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 648),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            section: 4,
            subSection: 1,
            maxLength: 500,
            posX: 42,
            posY: 549,
            width: 290,
            height: 105,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: [139, 227, 339, 442, 506],
            posY: 677),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 90,
            sigMaxHeight: 38,
            section: 6,
            posX: 80,
            posY: 757),
        Field(
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            section: 6,
            posX: 70,
            posY: 773),
        Field(
            type: FieldType.date,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            section: 6,
            posX: 70,
            posY: 785),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 90,
            sigMaxHeight: 38,
            section: 6,
            posX: 275,
            posY: 757),
        Field(
            duplicateFrom: 'instructor_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            section: 6,
            posX: 245,
            posY: 774),
        Field(
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            section: 6,
            posX: 245,
            posY: 786),
      ],
    );
  }
}
