import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class FcssForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [369, 382, 396, 411, 425, 439];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;

    String formName = 'forms/fcss.pdf';
    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training as indicated, have supervised the required session in accordance with the published';
    // int defaultGrade() => Authen.isTjo() ? -1 : -1;
    // bool defaultCheck = true;

    return f.Form(
      type: f.FormType.fcss,
      formName: 'FCSS',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName,
      dbTable: kFcssTable,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'TECHNICAL',
        'ABNORMAL',
        'TAKEOFF',
        'NON-TECHNICAL',
      ],
      formLabel: 'FCSS',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      ruler: false,
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [130, 175, 220],
            posYList: [83, 83, 83]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 100),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s License No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 332,
            posY: 86),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 350,
            posY: 99),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'evaluator_rank',
            label: 'Evaluator\'s Rank',
            type: FieldType.radio,
            listValue: ['CAPT'],
            stringValue: 'CAPT',
            intValue: 0,
            editable: false,
            section: 1,
            subSection: 2,
            posXList: [130],
            posYList: [108]),
        Field(
            name: 'evaluator_name',
            label: 'Evaluator\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 126),
        Field(
            name: 'evaluator_license_no',
            label: 'Evaluator License No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 332,
            posY: 112),
        Field(
            name: 'evaluator_id',
            label: 'Evaluator\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 350,
            posY: 125),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 485,
            posY: 87),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
            // stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            posX: 485,
            posY: 99),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 485,
            posY: 112),
        Field(
            name: 'ac_type',
            label: 'ACFT Type',
            type: FieldType.radio,
            listValue: ['A320', 'B737'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [488, 523],
            posYList: [122, 122]),
        Field(
            name: 'check_type',
            label: 'Screening Desciption',
            type: FieldType.radio,
            listValue: ['Command Upgrade', 'New Recruitment', 'Other'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [175, 273, 372],
            posYList: [136, 136, 136]),
        Field(
            name: 'check_type_other',
            label: 'Other...',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'Abracadabra' : '',
            posX: 410,
            posY: 140),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label: 'TAKEOFF',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 198),
        Field(
            name: 'q2',
            label: 'CLIMB',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 211),
        Field(
            name: 'q3',
            label: 'CRUISE',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 223),
        Field(
            name: 'q4_check',
            label: 'APPROACH.........',
            type: FieldType.checkbox,
            listValue: ['ILS RAW DATA', '2D-SELECTED', 'OTHER'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: [117, 188, 258],
            posY: 233),
        Field(
            name: 'q4_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            stringValue: 'FALSE'),
        Field(
            name: 'q4_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            stringValue: 'FALSE'),
        Field(
            name: 'q4_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            stringValue: 'FALSE'),
        Field(
            name: 'q4_detail',
            label: 'Other …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'VISUAL' : '',
            posX: 300,
            posY: 236),
        Field(
            name: 'q4',
            label: 'APPROACH.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 235),
        Field(
            name: 'q5',
            label: 'GO AROUND (IF APPLICABLE)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 247),
        Field(
            name: 'q6',
            label: 'MANUAL LANDING',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 259),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 450,
            posY: 200,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q7',
            label: 'REJECTED TAKEOFF (IF APPLICABLE)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 285),
        Field(
            name: 'q8_check',
            label: 'ENGINE.........',
            type: FieldType.checkbox,
            listValue: ['ENG STALL', 'ENGINE FAIL/FIRE AFTER V1'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [103, 162],
            posY: 296),
        Field(
            name: 'q8_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q8_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q8',
            label: 'ENGINE.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 298),
        Field(
            name: 'q9',
            label: 'UNRELIABLE AIRSPEED INDICATION',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 310),
        Field(
            name: 'q10_check',
            label: 'ELECTRICAL.........',
            type: FieldType.checkbox,
            listValue: ['ELEC EMER CONFIG', 'ALL AC/DC BUSS FAIL'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [123, 217],
            posY: 321),
        Field(
            name: 'q10_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q10_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q10',
            label: 'ELECTRICAL.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 323),
        Field(
            name: 'q11_check',
            label: 'DUAL HYD SYSTEM FAIL.........',
            type: FieldType.checkbox,
            listValue: ['B+G', 'G+Y', 'B+Y', 'OTHER'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [167, 198, 229, 259],
            posY: 334),
        Field(
            name: 'q11_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q11_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q11_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q11_check_3',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q11_detail',
            label: 'Other …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'ALL' : '',
            posX: 300,
            posY: 337),
        Field(
            name: 'q11',
            label: 'DUAL HYD SYSTEM FAIL.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 336),
        Field(
            name: 'q12_check',
            label: 'FLIGHT CONTROL.........',
            type: FieldType.checkbox,
            listValue: ['ABNORMAL SLATS/FLAPS', 'STABILIZER JAM'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [142, 257],
            posY: 346),
        Field(
            name: 'q12_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q12_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q12',
            label: 'FLIGHT CONTROL.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 348),
        Field(
            name: 'q13',
            label: 'FCU 1 + 2 FAULT',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 360),
        Field(
            name: 'q14',
            label: 'RA 1+2 FAULT',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 372),
        Field(
            name: 'q15_check',
            label: 'DUAL ADR.........',
            type: FieldType.checkbox,
            listValue: ['1+2', '2+3', '1+3'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [113, 142, 170],
            posY: 383),
        Field(
            name: 'q15_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q15_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q15_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'q15',
            label: 'DUAL ADR.........',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 384),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 450,
            posY: 286,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q16',
            label: 'CREW RESOURCE MANAGEMENT (CRM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 412),
        Field(
            name: 'q17',
            label: 'THREAT & ERROR MANAGEMENT (TEM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 424),
        Field(
            name: 'q18',
            label: 'ASSERTIVENESS & INTERPERSONAL SKILLS',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 436),
        Field(
            name: 'q19',
            label: 'SECURITY & SAFETY ATTITUDE',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 447),
        Field(
            name: 'q20',
            label: 'PUBLIC ADDRESS (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 458),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 450,
            posY: 413,
            width: 115,
            fontSize: 8),

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 480),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 480),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 526),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 538),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 550),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 562),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 574),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 585),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 597),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 610),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 621),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            section: 5,
            subSection: 1,
// isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 530,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            section: 6,
            subSection: 1,
            posXList: [138, 220, 340, 441, 504],
            posY: 652),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'evaluator_sig',
            label: 'Evaluator\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            section: 7,
            posX: 120,
            posY: 750),
        Field(
            duplicateFrom: 'evaluator_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            section: 7,
            posX: 80,
            posY: 766),
        Field(
// name: 'instructor_sig_date',
// label: 'Date',
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
// keyboardType: TextInputType.datetime,
            section: 7,
// stringValue:
//     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 80,
            posY: 777),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Pilot info.
        'pilot_rank': form.getStrVal('pilot_rank'),
        'pilot_name': form.getStrVal('pilot_name'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_id': form.getStrVal('pilot_id'),

        ///Instructor info.
        'evaluator_rank': form.getStrVal('evaluator_rank'),
        'evaluator_name': form.getStrVal('evaluator_name'),
        'evaluator_license_no': form.getStrVal('evaluator_license_no'),
        'evaluator_id': form.getStrVal('evaluator_id'),

        ///Check details
        'check_date': form.getStrVal('check_date'),
        'block_time': form.getStrVal('block_time'),
        'fstd_no': form.getStrVal('fstd_no'),
        'ac_type': form.getStrVal('ac_type'),
        'check_type': form.getStrVal('check_type'),
        'check_type_other': form.getStrVal('check_type_other'),

        ///Grading & Comment
        ///A
        'q1': form.getStrVal('q1'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4_check_0': form.getStrVal('q4_check_0'),
        'q4_check_1': form.getStrVal('q4_check_1'),
        'q4_check_2': form.getStrVal('q4_check_2'),
        'q4_detail': form.getStrVal('q4_detail'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8_check_0': form.getStrVal('q8_check_0'),
        'q8_check_1': form.getStrVal('q8_check_1'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10_check_0': form.getStrVal('q10_check_0'),
        'q10_check_1': form.getStrVal('q10_check_1'),
        'q10': form.getStrVal('q10'),
        'q11_check_0': form.getStrVal('q11_check_0'),
        'q11_check_1': form.getStrVal('q11_check_1'),
        'q11_check_2': form.getStrVal('q11_check_2'),
        'q11_check_3': form.getStrVal('q11_check_3'),
        'q11_detail': form.getStrVal('q11_detail'),
        'q11': form.getStrVal('q11'),
        'q12_check_0': form.getStrVal('q12_check_0'),
        'q12_check_1': form.getStrVal('q12_check_1'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15_check_0': form.getStrVal('q15_check_0'),
        'q15_check_1': form.getStrVal('q15_check_1'),
        'q15_check_2': form.getStrVal('q15_check_2'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),


        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),

        ///LANDING AND GO-AROUND
        'no_landing': form.getStrVal('no_landing'),
        'no_goaround': form.getStrVal('no_goaround'),

        ///COMPETENCY
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),

        ///RESULT
        'result': form.getStrVal('result'),
// 'instructor_sig_date': form.getStrVal('instructor_sig_date'),
      };
  }
}
