import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class LineTrainForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 290;
    int defaultGrade() => Authen.isTjo() ? 1 : -1;
    bool defaultCheck() => Authen.isTjo() ? true : false;
    // int defaultGrade() => Authen.isTjo() c? -1 : -1;
    // bool defaultCheck = true;

    return f.Form(
      type: f.FormType.lineTrain,
      formName: 'LINE TRAIN / CHECK',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: DateTime.now().isBefore(k1Jan26)
          ? 'forms/linetrain15.pdf'
          : 'forms/linetrain16.pdf',
      dbTable: kLineTrainTable,
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PRE-FLIGHT PREPARATION / TAXI',
        'TAKEOFF',
        'CLIMB / CRUISE / DESCENT',
        'APPROACH AND LANDING',
        'TAXI / POST-FLIGHT',
        'NON-TECHNICAL',
        'ADDITIONAL / OTHERS',
      ],
      formLabel: 'Line Train / Check',
      formLabelInfoField1: 'pilot_name',
      formLabelInfoField2: '',
      // ruler: true,
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Rank & Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'FO. John Doe' : '',
            posX: 148,
            posY: 101),
        Field(
            name: 'pilot_license_no',
            label: 'FCL / FIC / FEC No.',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 330,
            posY: 101),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No.(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 465,
            posY: 100),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_name',
            label: 'Instructor\'s Rank & Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 148,
            posY: 117),
        Field(
            name: 'instructor_cert_no',
            label: 'FCL / FIC / FEC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 330,
            posY: 117),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No.(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 465,
            posY: 116),

        ///.....................................................................
        ///Examminer / CAAT
        ///.....................................................................
        Field(
            name: 'examiner_name',
            label: DateTime.now().isBefore(k1Jan26)
                ? 'Examiner\'s Rank & Name (Applicable only for check flight)'
                : 'Checker\'s Rank & Name (Applicable only for check flight)',
            type: FieldType.string,
            isMandatory: false,
            section: 1,
            subSection: 3,
            stringValue: Authen.isTjo() ? 'Christopher Pike' : '',
            posX: 148,
            posY: 133),
        Field(
            name: 'examiner_license_no',
            label: 'FCL / FIC / FEC No.',
            type: FieldType.string,
            isMandatory: false,
            section: 1,
            subSection: 3,
            stringValue: Authen.isTjo() ? 'NCC-1701' : '',
            posX: 330,
            posY: 133),
        Field(
            name: 'examiner_id',
            label: DateTime.now().isBefore(k1Jan26)
                ? 'Examiner\'s Staff No.(xxxx)'
                : 'Checker\'s Staff No.(xxxx)',
            type: FieldType.string,
            isMandatory: false,
            section: 1,
            subSection: 3,
            maxLength: 10,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0000' : '',
            posX: 450,
            posY: 133),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'course',
            label: 'Training Course',
            type: FieldType.radio,
            listValue: [
              'Initial Type Rating',
              // 'Transition',
              'Transition / Conversion',
              'On Type',
              'Command Upgrade',
              'Requalification',
              'Other'
            ],
            intValue: kInitChoice,
            section: 2,
            subSection: 1,
            posXList: [45, 45, 45, 45, 45, 45],
            posYList: [179, 194, 210, 225, 240, 255]),
        Field(
            name: 'other_course',
            label: 'Other(if selected)',
            type: FieldType.string,
            section: 2,
            subSection: 1,
            isMandatory: false,
            maxLength: 12,
            posX: 76,
            posY: 251),
        Field(
            name: 'check_type',
            label: 'Type of Training',
            type: FieldType.checkbox,
            listValue: [
              'Aircraft Base Training',
              'Aircraft Base Check',
              'LIFUS Training',
              'LIFUS Check',
              'Base Release',
              'Initial Line Check',
              'Other',
            ],
            checkBoxValue: [
              defaultCheck(),
              defaultCheck(),
              defaultCheck(),
              defaultCheck(),
              defaultCheck(),
              defaultCheck(),
              defaultCheck()
              // defaultCheck()
            ],
            // isMandatory: false,
            section: 2,
            subSection: 2,
            posYList: [179, 194, 210, 225, 240, 255, 271],
            posX: 149),
        Field(
            name: 'check_type_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_3',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_4',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_5',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        Field(
            name: 'check_type_6',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),
        // Field(
        //     name: 'check_type_7',
        //     type: FieldType.string,
        //     input: false,
        //     writePdf: false,
        //     isMandatory: false,
        //     section: 2,
        //     subSection: 2,
        //     stringValue: 'FALSE'),
        Field(
            name: 'other_type',
            label: 'Other(if selected)',
            type: FieldType.string,
            section: 2,
            subSection: 2,
            isMandatory: false,
            maxLength: 12,
            posX: 178,
            posY: 282),
        Field(
            name: 'date_1',
            label: 'Sector 1 Date',
            // type: FieldType.string,
            type: FieldType.date,
            page: 1,
            section: 2,
            subSection: 3,
            keyboardType: TextInputType.datetime,
            stringValue: DateFormat('dd-MMM-yy').format(DateTime.now()),
            dateTimeValue: DateTime.now(),
            posX: 356,
            posY: 198),
        Field(
            name: 'ac_type_1',
            label: 'Sector 1 A/C Type',
            type: FieldType.radio,
            listValue: ['A320', 'A321', 'B737'],
            intValue: kInitChoice,
            section: 2,
            subSection: 3,
            posXList: [337, 371, 406],
            posY: 179),
        Field(
            name: 'ac_reg_1',
            label: 'Sector 1 Registration (HS-___)',
            type: FieldType.string,
            stringValue: 'V',
            section: 2,
            subSection: 3,
            maxLength: 3,
            minLength: 3,
            posX: 377,
            posY: 243),
        Field(
            name: 'flt_no_1',
            label: 'Sector 1 Flight No. (VZ___)',
            type: FieldType.string,
            section: 2,
            subSection: 3,
            maxLength: 4,
            keyboardType: TextInputType.number,
            posX: 376,
            posY: 213),
        Field(
            name: 'route_1',
            label: 'Sector 1 Route (XXX-XXX)',
            type: FieldType.string,
            section: 2,
            subSection: 3,
            maxLength: 7,
            posX: 357,
            posY: 228),
        Field(
            name: 'duty_1',
            label: 'Sector 1 Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: kInitChoice,
            section: 2,
            subSection: 3,
            posXList: [360, 386],
            posY: 255),

        Field(
            name: 'date_2',
            label: 'Sector 2 Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            subSection: 4,
            keyboardType: TextInputType.datetime,
            stringValue: DateFormat('dd-MMM-yy').format(DateTime.now()),
            dateTimeValue: DateTime.now(),
            posX: 474,
            posY: 198),
        Field(
            name: 'ac_type_2',
            label: 'Sector 2 A/C Type',
            type: FieldType.radio,
            listValue: ['A320', 'A321', 'B737'],
            intValue: kInitChoice,
            section: 2,
            subSection: 4,
            posXList: [455, 489, 524],
            posY: 179),
        Field(
            name: 'ac_reg_2',
            label: 'Sector 2 Registration (HS-___)',
            type: FieldType.string,
            stringValue: 'V',
            section: 2,
            subSection: 4,
            maxLength: 3,
            minLength: 3,
            posX: 494,
            posY: 243),
        Field(
            name: 'flt_no_2',
            label: 'Sector 2 Flight No. (VZ___)',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            maxLength: 4,
            keyboardType: TextInputType.number,
            posX: 493,
            posY: 213),
        Field(
            name: 'route_2',
            label: 'Sector 2 Route (XXX-XXX)',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            maxLength: 7,
            posX: 475,
            posY: 228),
        Field(
            name: 'duty_2',
            label: 'Sector 2 Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: kInitChoice,
            section: 2,
            subSection: 4,
            posXList: [478, 504],
            posY: 255),

        Field(
            name: 'accum_pf',
            label: 'Accumulated PF at the end of this flight',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 5,
            keyboardType: TextInputType.number,
            maxLine: 3,
            posX: 357,
            posY: 290),
        Field(
            name: 'accum_pm',
            label: 'Accumulated PM at the end of this flight',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 5,
            keyboardType: TextInputType.number,
            maxLine: 3,
            posX: 515,
            posY: 290),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label:
                'Flight documents, Security check, Flight crew and Cabin crew briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 361),
        Field(
            name: 'q2',
            label: 'Fuel policy / FMGS preparation / X-check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 376),
        Field(
            name: 'q3',
            label: 'Aircraft status / MEL',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 390),
        Field(
            name: 'q4',
            label: 'Aircraft safety inspection (Exterior and Interior)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 404),
        Field(
            name: 'q5',
            label:
                'Load sheet / Takeoff performance calculation / EFB management',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 419),
        Field(
            name: 'q6',
            label: 'Takeoff briefing / TEM / NAVAIDS setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 433),
        Field(
            name: 'q7',
            label:
                'Engine Start (Time management) / Monitoring engine start parameter',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 448),
        Field(
            name: 'q8',
            label: 'ATC communication / Ground crew coordination',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 463),
        Field(
            name: 'q9',
            label: 'Taxi technique / Taxi monitoring and support',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 476),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 361,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q10',
            label:
                'Takeoff technique (Rotation rate, takeoff attitude, Tail strike awareness)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 505),
        Field(
            name: 'q11',
            label: 'Noise Abatement procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 520),
        Field(
            name: 'q12',
            label: 'PF duties / PM Support (Procedures and Callouts)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 534),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 506,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q13',
            label: 'SID / ATC compliance / PBN operations',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 563),
        Field(
            name: 'q14',
            label: 'Climb technique / Procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 577),
        Field(
            name: 'q15',
            label: 'Altitude selection / Step climb / RVSM operations',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 591),
        Field(
            name: 'q16',
            label:
                'In-flight planning / Re-planning (e.g. fuel management) / Emergency procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 605),
        Field(
            name: 'q17',
            label: 'Enroute Communications / ATC procedure and compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 620),
        Field(
            name: 'q18',
            label: 'WX avoidance procedures (CAT / Wake Turbulence, etc.)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 634),
        Field(
            name: 'q19',
            label: 'Descent planning / Briefing / TEM / Situation awareness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 648),
        Field(
            name: 'q20',
            label: 'Profile management / Speed / Altitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 663),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 563,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q21',
            label: 'STAR / ATC compliance / PBN operations',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 692),
        Field(
            name: 'q22',
            label: 'Approach procedures (3D and 2D approach)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 706),
        Field(
            name: 'q23',
            label:
                'Aircraft configuration (Selection of landing flaps) and energy management',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 720),
        Field(
            name: 'q24',
            label: 'Stabilized approach criteria compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 735),
        Field(
            name: 'q25',
            label: 'Landing technique',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 749),
        Field(
            name: 'q26',
            label:
                'Reversers / Braking / Runway clearance (Vacating) / Runway occupancy time',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 764),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 692,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q27',
            label: 'Taxi-in technique / Taxi monitoring and PM support',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 112),
        Field(
            name: 'q28',
            label: 'Parking / Shut Down procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 126),
        Field(
            name: 'q29',
            label: 'Post-Flight documents procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 140),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 112,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q30',
            label: 'Crew Resource Management (CRM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 169),
        Field(
            name: 'q31',
            label: 'Threat & Error Management (TEM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 183),
        Field(
            name: 'q32',
            label: 'Assertiveness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 198),
        Field(
            name: 'q33',
            label: 'Interpersonal Skills',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 212),
        Field(
            name: 'q34',
            label: 'Security-Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 226),
        Field(
            name: 'q35',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 241),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 169,
            width: 115,
            fontSize: 8),
        Field(
            name: 'q36',
            label:
                'Green operations policy (Single engine taxi, Less flaps landing, etc.)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 270),
        Field(
            name: 'q37_detail',
            label: 'Additional 1',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 287),
        Field(
            name: 'q37',
            label: 'Additional 1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            posXList: _gradePosX,
            posY: 284),
        Field(
            name: 'q38_detail',
            label: 'Additional 2',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 301),
        Field(
            name: 'q38',
            label: 'Additional 2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            posXList: _gradePosX,
            posY: 298),
        Field(
            name: 'q39_detail',
            label: 'Additional 3',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 316),
        Field(
            name: 'q39',
            label: 'Additional 3',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            posXList: _gradePosX,
            posY: 313),
        Field(
            name: 'q40_detail',
            label: 'Additional 4',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 330),
        Field(
            name: 'q40',
            label: 'Additional 4',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            posXList: _gradePosX,
            posY: 327),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 445,
            posY: 270,
            width: 115,
            fontSize: 8),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 378),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 389),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 400),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 410),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 421),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 431),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 442),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 453),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 4,
            subSection: 1,
            posXList: _gradePosX,
            posY: 464),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 381,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: [138, 228, 339, 440, 504],
            posY: 489),
        Field(
            name: 'additional_note',
            label: 'Additional notes (if applicable)',
            type: FieldType.string,
            page: 2,
            section: 5,
            subSection: 1,
            isMandatory: false,
            maxLength: 1000,
            posX: 42,
            posY: 674,
            width: 510,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 6,
            posX: 70,
            posY: 600),
        Field(
            duplicateFrom: 'pilot_name',
            input: false,
            isMandatory: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            fontSize: 7,
            posX: 66,
            posY: 624),
        Field(
            // name: 'pilot_sig_date',
            // label: 'Date',
            duplicateFrom: 'date_1',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            // keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 66,
            posY: 638),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 6,
            posX: 197,
            posY: 600),
        Field(
            duplicateFrom: 'instructor_name',
            input: false,
            isMandatory: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            fontSize: 7,
            posX: 199,
            posY: 624),
        Field(
            // name: 'instructor_sig_date',
            // label: 'Date',
            duplicateFrom: 'date_1',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            // keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 199,
            posY: 638),

        Field(
            name: 'examiner_result',
            label: 'Result',
            type: FieldType.radio,
            isMandatory: false,
            listValue: [
              'Pass',
              'Fail',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 2,
            posXList: [305, 342],
            posY: 550),
        Field(
            name: 'examiner_sig',
            label: DateTime.now().isBefore(k1Jan26)
                ? 'Examiner\'s Signature'
                : 'Checker\'s Signature',
            isMandatory: false,
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 40,
            page: 2,
            section: 6,
            subSection: 2,
            posX: 329,
            posY: 600),
        Field(
            duplicateFrom: 'examiner_name',
            input: false,
            isMandatory: false,
            type: FieldType.string,
            page: 2,
            section: 6,
            fontSize: 7,
            posX: 330,
            posY: 624),
        Field(
            name: 'examiner_sig_date',
            label: 'Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 2,
            section: 6,
            isMandatory: false,
            stringValue: kBlankText,
            // DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 330,
            posY: 638),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Pilot info.
        'pilot_name': form.getStrVal('pilot_name'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_id': form.getStrVal('pilot_id'),

        ///Instructor info.
        'instructor_name': form.getStrVal('instructor_name'),
        'instructor_cert_no': form.getStrVal('instructor_cert_no'),
        'instructor_id': form.getStrVal('instructor_id'),

        ///Examiner / CAAT info.
        'examiner_name': form.getStrVal('examiner_name'),
        'examiner_license_no': form.getStrVal('examiner_license_no'),
        'examiner_id': form.getStrVal('examiner_id'),

        ///Check details
        'course': form.getStrVal('course'),
        'other_course': form.getStrVal('other_course'),
        'check_type_0': form.getStrVal('check_type_0'),
        'check_type_1': form.getStrVal('check_type_1'),
        'check_type_2': form.getStrVal('check_type_2'),
        'check_type_3': form.getStrVal('check_type_3'),
        'check_type_4': form.getStrVal('check_type_4'),
        'check_type_5': form.getStrVal('check_type_5'),
        'check_type_6': form.getStrVal('check_type_6'),
        // 'check_type_7': form.getStrVal('check_type_7'),
        'other_type': form.getStrVal('other_type'),

        ///Sector
        'date_1': form.getStrVal('date_1'),
        'ac_type_1': form.getStrVal('ac_type_1'),
        'ac_reg_1': form.getStrVal('ac_reg_1'),
        'flt_no_1': form.getStrVal('flt_no_1'),
        'route_1': form.getStrVal('route_1'),
        'duty_1': form.getStrVal('duty_1'),
        'date_2': form.getStrVal('date_2'),
        'ac_type_2': form.getStrVal('ac_type_2'),
        'ac_reg_2': form.getStrVal('ac_reg_2'),
        'flt_no_2': form.getStrVal('flt_no_2'),
        'route_2': form.getStrVal('route_2'),
        'duty_2': form.getStrVal('duty_2'),

        'accum_pf': form.getStrVal('accum_pf'),
        'accum_pm': form.getStrVal('accum_pm'),

        ///Grading & Comment
        'q1': form.getStrVal('q1'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25': form.getStrVal('q25'),
        'q26': form.getStrVal('q26'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37_detail': form.getStrVal('q37_detail'),
        'q37': form.getStrVal('q37'),
        'q38_detail': form.getStrVal('q38_detail'),
        'q38': form.getStrVal('q38'),
        'q39_detail': form.getStrVal('q39_detail'),
        'q39': form.getStrVal('q39'),
        'q40_detail': form.getStrVal('q40_detail'),
        'q40': form.getStrVal('q40'),

        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qf_comment': form.getStrVal('qf_comment'),
        'qg_comment': form.getStrVal('qg_comment'),

        ///COMPETENCY
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),
        'additional_note': form.getStrVal('additional_note'),

        ///RESULT
        'result': form.getStrVal('result'),
        'examiner_result': form.getStrVal('examiner_result'),
        // 'pilot_sig_date': form.getStrVal('pilot_sig_date'),
        // 'instructor_sig_date': form.getStrVal('instructor_sig_date'),
        'examiner_sig_date': form.getStrVal('examiner_sig_date'),
      };
  }
}
