import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class LineCheckForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _boolList = ['YES', 'NO'];
    List<double> _gradePosX = [307, 324, 342, 359, 377, 396];
    List<double> _competentPosX = [165, 183, 201, 219, 237, 256];
    int gradeCommentMaxLen = 180;
    return f.Form(
      type: f.FormType.lineCheck,
      formName: 'Line Check',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: 'forms/linecheck.pdf',
      dbTable: kLineCheckTable,
      fontSize: 10,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Briefing Items',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PRE-FLIGHT PREPARATION AND ENGINE START',
        'TAXI AND TAKEOFF',
        'CLIMB and CRUISE',
        'DESCENT / APPROACH AND LANDING',
        'NON-TECHNICAL',
      ],
      formLabel: 'Line Check',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      dateFormat: 'dd/MM/yyyy',
      fields: [
        ///.....................................................................
        ///PILOT
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Pilot Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'FO.'],
            intValue: kInitChoice,
            section: 1,
            subSection: 1,
            page: 1,
            posXList: [152, 178],
            posYList: [100, 100]),
        Field(
            name: 'pilot_name',
            label: 'Pilot Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            // stringValue: 'Teerachart Jongkoldee',
            posX: 200,
            posY: 102),
        Field(
            name: 'pilot_license_no',
            label: 'Pilot License No.',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            // stringValue: 'TH.FCL.0001234',
            posX: 152,
            posY: 127),
        Field(
            name: 'pilot_id',
            label: 'Pilot Staff ID No.(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            // stringValue: '0895',
            posX: 167,
            posY: 149),

        ///.....................................................................
        ///EXAMINER
        ///.....................................................................
        Field(
            name: 'examiner_rank',
            label: 'Examiner Rank',
            type: FieldType.radio,
            listValue: ['DCP', 'FI-A', 'SV'],
            intValue: kInitChoice,
            section: 1,
            subSection: 2,
            page: 1,
            posXList: [360, 385, 410],
            posYList: [100, 100, 100]),
        Field(
            name: 'examiner_name',
            label: 'Examiner Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            posX: 430,
            posY: 102),
        Field(
            name: 'examiner_license_no',
            label: 'Examiner License / Certificate No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            posX: 360,
            posY: 127),
        Field(
            name: 'examiner_id',
            label: 'Examiner Staff ID No.(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            posX: 375,
            posY: 149),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'type_of_check',
            label: 'Type Of Check',
            type: FieldType.radio,
            listValue: [
              'Initial',
              'Annual',
              'Recency',
              'Requalification',
              'Other'
            ],
            intValue: kInitChoice,
            section: 2,
            subSection: 1,
            page: 1,
            posXList: [45, 45, 45, 45, 45],
            posYList: [195, 212, 229, 245, 262]),
        Field(
            name: 'other_type',
            label: 'Other(if selected)',
            type: FieldType.string,
            section: 2,
            subSection: 1,
            isMandatory: false,
            posX: 78,
            posY: 262),
        Field(
            name: 'ac_type_1',
            label: 'Sector 1 A/C Type',
            type: FieldType.radio,
            listValue: ['A320', 'A321'],
            intValue: kInitChoice,
            page: 1,
            section: 2,
            subSection: 2,
            posXList: [345, 381],
            posYList: [179, 179]),
        Field(
            name: 'ac_reg_1',
            label: 'Sector 1 Registration (HS-___)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 2,
            maxLength: 3,
            minLength: 3,
            posX: 370,
            posY: 246),
        Field(
            name: 'date_1',
            label: 'Sector 1 Date',
            // type: FieldType.string,
            type: FieldType.date,
            page: 1,
            section: 2,
            subSection: 2,
            keyboardType: TextInputType.datetime,
            stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
            dateTimeValue: DateTime.now(),
            posX: 345,
            posY: 197),
        Field(
            name: 'flt_no_1',
            label: 'Sector 1 Flight No. (VZ___)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            posX: 363,
            posY: 212),
        Field(
            name: 'from_1',
            label: 'Sector 1 From (ICAO)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 2,
            maxLength: 4,
            minLength: 4,
            stringValue: 'VTBS',
            posX: 345,
            posY: 229),
        Field(
            name: 'to_1',
            label: 'Sector 1 To (ICAO)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 2,
            maxLength: 4,
            minLength: 4,
            posX: 378,
            posY: 229),
        Field(
            name: 'duty_1',
            label: 'Sector 1 Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: kInitChoice,
            page: 1,
            section: 2,
            subSection: 2,
            posXList: [353, 380],
            posYList: [262, 262]),
        Field(
            name: 'ac_type_2',
            label: 'Sector 2 A/C Type',
            type: FieldType.radio,
            listValue: ['A320', 'A321'],
            intValue: kInitChoice,
            page: 1,
            section: 2,
            subSection: 3,
            posXList: [468, 504],
            posYList: [179, 179]),
        Field(
            name: 'ac_reg_2',
            label: 'Sector 2 Registration (HS-___)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 3,
            maxLength: 3,
            minLength: 3,
            posX: 493,
            posY: 246),
        Field(
            name: 'date_2',
            label: 'Sector 2 Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 1,
            section: 2,
            subSection: 3,
            stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
            dateTimeValue: DateTime.now(),
            posX: 468,
            posY: 197),
        Field(
            name: 'flt_no_2',
            label: 'Sector 2 Flight No. (VZ___)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 3,
            maxLength: 4,
            keyboardType: TextInputType.number,
            posX: 486,
            posY: 212),
        Field(
            name: 'from_2',
            label: 'Sector 2 From (ICAO)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 3,
            maxLength: 4,
            minLength: 4,
            posX: 468,
            posY: 229),
        Field(
            name: 'to_2',
            label: 'Sector 2 To (ICAO)',
            type: FieldType.string,
            page: 1,
            section: 2,
            subSection: 3,
            maxLength: 4,
            minLength: 4,
            stringValue: 'VTBS',
            posX: 501,
            posY: 229),
        Field(
            name: 'duty_2',
            label: 'Sector 2 Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: kInitChoice,
            page: 1,
            section: 2,
            subSection: 3,
            posXList: [476, 503],
            posYList: [262, 262]),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'a_1',
            label:
                'Flight documents, Security check, Flight crew and Cabin crew briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [360, 360, 360, 360, 360, 360]),
        Field(
            name: 'a_2',
            label: 'Fuel policy / FMGS preparation / X-check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [373, 373, 373, 373, 373, 373]),
        Field(
            name: 'a_3',
            label: 'Aircraft status / MEL',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [386, 386, 386, 386, 386, 386]),
        Field(
            name: 'a_4',
            label: 'Aircraft safety inspection (Exterior and Internal)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [399, 399, 399, 399, 399, 399]),
        Field(
            name: 'a_5',
            label: 'Load sheet / Takeoff performance calculation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [412, 412, 412, 412, 412, 412]),
        Field(
            name: 'a_6',
            label: 'Takeoff briefing / TEM / NAVAIDS setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [425, 425, 425, 425, 425, 425]),
        Field(
            name: 'a_7',
            label: 'Timely Engine Start / Monitoring Engine Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posYList: [439, 439, 439, 439, 439, 439]),
        Field(
            name: 'a_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 410,
            posY: 360,
            width: 160,
            height: 100,
            fontSize: 8),
        Field(
            name: 'b_8',
            label: 'ATC / Ground crew coordination',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posYList: [466, 466, 466, 466, 466, 466]),
        Field(
            name: 'b_9',
            label: 'Taxi technique',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posYList: [479, 479, 479, 479, 479, 479]),
        Field(
            name: 'b_10',
            label: 'Takeoff techique',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posYList: [492, 492, 492, 492, 492, 492]),
        Field(
            name: 'b_11',
            label: 'SID / ATC compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: [307, 324, 342, 359, 377, 396],
            posYList: [505, 505, 505, 505, 505, 505]),
        Field(
            name: 'b_12',
            label: 'Noise Abatement procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posYList: [518, 518, 518, 518, 518, 518]),
        Field(
            name: 'b_13',
            label: 'PM Support / Callouts / Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posYList: [531, 531, 531, 531, 531, 531]),
        Field(
            name: 'b_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 410,
            posY: 466,
            width: 160,
            height: 100,
            fontSize: 8),
        Field(
            name: 'c_14',
            label: 'Climb technique / Procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posYList: [559, 559, 559, 559, 559, 559]),
        Field(
            name: 'c_15',
            label: 'Altitude selection / Step climb',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posYList: [572, 572, 572, 572, 572, 572]),
        Field(
            name: 'c_16',
            label: 'In-flight planning / Re-planning / Emergency procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posYList: [585, 585, 585, 585, 585, 585]),
        Field(
            name: 'c_17',
            label: 'Enroute Comms / ATC procedure and compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posYList: [598, 598, 598, 598, 598, 598]),
        Field(
            name: 'c_18',
            label: 'CAT / Wake Turbulence / WX Avoidance procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posYList: [611, 611, 611, 611, 611, 611]),
        Field(
            name: 'c_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 410,
            posY: 559,
            width: 160,
            height: 100,
            fontSize: 8),
        Field(
            name: 'd_19',
            label: 'Descent planning / Briefing / TEM / Situation awareness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [639, 639, 639, 639, 639, 639]),
        Field(
            name: 'd_20',
            label:
                'Profile management / Speed / Altitude / Aircraft configuration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [652, 652, 652, 652, 652, 652]),
        Field(
            name: 'd_21',
            label: 'STAR / ATC compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [665, 665, 665, 665, 665, 665]),
        Field(
            name: 'd_22',
            label: 'Approach procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [678, 678, 678, 678, 678, 678]),
        Field(
            name: 'd_23',
            label: 'Stabilized Approach Criteria',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [691, 691, 691, 691, 691, 691]),
        Field(
            name: 'd_24',
            label: 'Landing technique',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [704, 704, 704, 704, 704, 704]),
        Field(
            name: 'd_25',
            label:
                'Reversers / Braking / Runway clearance (Vacating) / Runway occupancy time',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [725, 725, 725, 725, 725, 725]),
        Field(
            name: 'd_26',
            label: 'Parking / Shut Down procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [738, 738, 738, 738, 738, 738]),
        Field(
            name: 'd_27',
            label: 'Post-Flight documents / Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [751, 751, 751, 751, 751, 751]),
        Field(
            name: 'd_28',
            label: 'PM support',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posYList: [764, 764, 764, 764, 764, 764]),
        Field(
            name: 'd_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 410,
            posY: 639,
            width: 160,
            height: 100,
            fontSize: 8),
        Field(
            name: 'e_29',
            label: 'Crew Resource Management (CRM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [114, 114, 114, 114, 114, 114]),
        Field(
            name: 'e_30',
            label: 'Threat & Error Management (TEM)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [127, 127, 127, 127, 127, 127]),
        Field(
            name: 'e_31',
            label: 'Assertiveness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [140, 140, 140, 140, 140, 140]),
        Field(
            name: 'e_32',
            label: 'Interpersonal Skills',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [153, 153, 153, 153, 153, 153]),
        Field(
            name: 'e_33',
            label: 'Security-Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [166, 166, 166, 166, 166, 166]),
        Field(
            name: 'e_34',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posYList: [179, 179, 179, 179, 179, 179]),
        Field(
            name: 'e_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            posX: 410,
            posY: 114,
            width: 160,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///BRIEFING ITEM
        ///.....................................................................
        Field(
            name: 'brief_1',
            label: 'Hard Landing Awareness',
            type: FieldType.radio,
            listValue: _boolList,
            intValue: kInitChoice,
            page: 2,
            section: 4,
            subSection: 1,
            posXList: [307, 324],
            posYList: [262, 262]),
        Field(
            name: 'brief_2',
            label: 'Stabilized Approach Technique',
            type: FieldType.radio,
            listValue: _boolList,
            intValue: kInitChoice,
            page: 2,
            section: 4,
            subSection: 1,
            posXList: [307, 324],
            posYList: [275, 275]),
        Field(
            name: 'brief_3',
            label: 'Intercept From Above',
            type: FieldType.radio,
            listValue: _boolList,
            intValue: kInitChoice,
            page: 2,
            section: 4,
            subSection: 1,
            posXList: [307, 324],
            posYList: [288, 288]),
        Field(
            name: 'brief_4',
            label: 'Green Operations and Fuel Policy',
            type: FieldType.radio,
            listValue: _boolList,
            intValue: kInitChoice,
            page: 2,
            section: 4,
            subSection: 1,
            posXList: [307, 324],
            posYList: [301, 301]),
        Field(
            name: 'brief_5',
            label: 'Other',
            type: FieldType.radio,
            listValue: _boolList,
            intValue: kInitChoice,
            page: 2,
            section: 4,
            subSection: 1,
            posXList: [307, 324],
            posYList: [314, 314]),
        Field(
            name: 'brief_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            isMandatory: false,
            maxLength: 300,
            posX: 342,
            posY: 264,
            width: 220,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///COMPETENCY ASSESSMENT AND COMMENTS
        ///.....................................................................
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [399, 399, 399, 399, 399, 399]),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [412, 412, 412, 412, 412, 412]),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [425, 425, 425, 425, 425, 425]),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [440, 440, 440, 440, 440, 440]),
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [453, 453, 453, 453, 453, 453]),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [466, 466, 466, 466, 466, 466]),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [481, 481, 481, 481, 481, 481]),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [494, 494, 494, 494, 494, 494]),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: kInitChoice,
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _competentPosX,
            posYList: [507, 507, 507, 507, 507, 507]),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            page: 2,
            section: 5,
            subSection: 1,
            isMandatory: false,
            maxLength: 500,
            posX: 280,
            posY: 401,
            width: 280,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: ['Not Competent', 'Competent'],
            intValue: kInitChoice,
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [145, 145],
            posYList: [549, 590]),
        Field(
            name: 'competent_level',
            label: 'Competent Level',
            type: FieldType.radio,
            listValue: [
              'Improvement Required',
              'Average',
              'Above Average',
              'Good'
            ],
            intValue: kInitChoice,
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [215, 215, 215, 215],
            posYList: [565, 582, 599, 616]),
        Field(
            name: 'result_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 6,
            subSection: 1,
            isMandatory: false,
            maxLength: 300,
            posX: 324,
            posY: 552,
            width: 230,
            height: 100,
            fontSize: 8),
        Field(
            name: 'pilot_sig',
            label: 'Pilot\'s Signature',
            type: FieldType.signature,
            sigWidth: 100,
            sigMaxHeight: 60,
            page: 2,
            section: 7,
            posX: 80,
            posY: 720),
        Field(
            // name: 'PILOT_NAME',
            // label: 'Pilot Name',
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 741),
        Field(
            name: 'pilot_sig_date',
            label: 'Date',
            // input: false,
            // mandatory: true,
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
            stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
            dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 757),

        ///++++++++++++++++++++++++++++++++++++++++++++++++
        Field(
            name: 'examiner_sig',
            label: 'Examiner\'s Signature',
            type: FieldType.signature,
            sigWidth: 100,
            sigMaxHeight: 60,
            page: 2,
            section: 7,
            posX: 250,
            posY: 720),
        Field(
            // name: 'PILOT_NAME',
            // label: 'Pilot Name',
            duplicateFrom: 'examiner_name',
            input: false,
            isMandatory: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 250,
            posY: 741),
        Field(
            name: 'examiner_sig_date',
            label: 'Date',
            // input: false,
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            dateTimeValue: DateTime.now(),
            // mandatory: false,
            page: 2,
            section: 7,
            stringValue: DateFormat('dd/MM/yyyy').format(DateTime.now()),
            posX: 250,
            posY: 757),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        //----------------------------------------------------------------------
        //HEADER
        //----------------------------------------------------------------------
        //Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',
        //----------------------------------------------------------------------
        //ITEM
        //----------------------------------------------------------------------
        //Pilot info.
        'pilot_rank': form.getStrVal('pilot_rank'),
        'pilot_id': form.getStrVal('pilot_id'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_name': form.getStrVal('pilot_name'),

        //Examiner info.
        'examiner_rank': form.getStrVal('examiner_rank'),
        'examiner_id': form.getStrVal('examiner_id'),
        'examiner_license_no': form.getStrVal('examiner_license_no'),
        'examiner_name': form.getStrVal('examiner_name'),

        //Check type
        'type_of_check': form.getStrVal('type_of_check'),
        'other_type': form.getStrVal('other_type'),

        //Sector#1
        'date_1': form.getStrVal('date_1'),
        'ac_type_1': form.getStrVal('ac_type_1'),
        'ac_reg_1': form.getStrVal('ac_reg_1'),
        'flt_no_1': form.getStrVal('flt_no_1'),
        'from_1': form.getStrVal('from_1'),
        'to_1': form.getStrVal('to_1'),
        'duty_1': form.getStrVal('duty_1'),

        //Sector#2
        'date_2': form.getStrVal('date_2'),
        'ac_type_2': form.getStrVal('ac_type_2'),
        'ac_reg_2': form.getStrVal('ac_reg_2'),
        'flt_no_2': form.getStrVal('flt_no_2'),
        'from_2': form.getStrVal('from_2'),
        'to_2': form.getStrVal('to_2'),
        'duty_2': form.getStrVal('duty_2'),

        //Grading & Comment
        //A
        'a_1': form.getStrVal('a_1'),
        'a_2': form.getStrVal('a_2'),
        'a_3': form.getStrVal('a_3'),
        'a_4': form.getStrVal('a_4'),
        'a_5': form.getStrVal('a_5'),
        'a_6': form.getStrVal('a_6'),
        'a_7': form.getStrVal('a_7'),
        'a_comment': form.getStrVal('a_comment'),
        //B
        'b_8': form.getStrVal('b_8'),
        'b_9': form.getStrVal('b_9'),
        'b_10': form.getStrVal('b_10'),
        'b_11': form.getStrVal('b_11'),
        'b_12': form.getStrVal('b_12'),
        'b_13': form.getStrVal('b_13'),
        'b_comment': form.getStrVal('b_comment'),
        //C
        'c_14': form.getStrVal('c_14'),
        'c_15': form.getStrVal('c_15'),
        'c_16': form.getStrVal('c_16'),
        'c_17': form.getStrVal('c_17'),
        'c_18': form.getStrVal('c_18'),
        'c_comment': form.getStrVal('c_comment'),
        //D
        'd_19': form.getStrVal('d_19'),
        'd_20': form.getStrVal('d_20'),
        'd_21': form.getStrVal('d_21'),
        'd_22': form.getStrVal('d_22'),
        'd_23': form.getStrVal('d_23'),
        'd_24': form.getStrVal('d_24'),
        'd_25': form.getStrVal('d_25'),
        'd_26': form.getStrVal('d_26'),
        'd_27': form.getStrVal('d_27'),
        'd_28': form.getStrVal('d_28'),
        'd_comment': form.getStrVal('d_comment'),
        //E
        'e_29': form.getStrVal('e_29'),
        'e_30': form.getStrVal('e_30'),
        'e_31': form.getStrVal('e_31'),
        'e_32': form.getStrVal('e_32'),
        'e_33': form.getStrVal('e_33'),
        'e_34': form.getStrVal('e_34'),
        'e_comment': form.getStrVal('e_comment'),
        //BRIEFING
        'brief_1': form.getStrVal('brief_1'),
        'brief_2': form.getStrVal('brief_2'),
        'brief_3': form.getStrVal('brief_3'),
        'brief_4': form.getStrVal('brief_4'),
        'brief_5': form.getStrVal('brief_5'),
        'brief_comment': form.getStrVal('brief_comment'),
        //COMPETENCY
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),
        //RESULT
        'result': form.getStrVal('result'),
        'competent_level': form.getStrVal('competent_level'),
        'result_comment': form.getStrVal('result_comment'),

        'pilot_sig_date': form.getStrVal('pilot_sig_date'),
        'examiner_sig_date': form.getStrVal('examiner_sig_date'),
      };
  }
}
