import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class Ppc5Form {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;
    String defaultComment = '';
    // 'I am being a person authorized by TVJ and/or CAAT to conduct such training'
    // ' as indicated, have supervised the required session in '
    // 'accordance with the published';

    return f.Form(
      type: f.FormType.ppc5,
      formName: 'PPC',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: 'forms/ppc5.pdf',
      dbTable: kPPC5Table,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      // fontSize: 9,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PREFLIGHT PREPARATION AND GROUND OPERATIONS',
        'TAKEOFF',
        'INFLIGHT MANEUVERS AND PROCEDURES',
        'AIRCRAFT SYSTEM MALFUNCTION (SELECT MINIMUM 3 ITEMS)',
        'ABNORMAL AND EMERGENCY PROCEDURE (SELECT MINIMUM 3 ITEMS)',
        'MISSED APPROACH PROCEDURES',
        'LANDINGS AND AFTER LANDING PROCEDURES',
        'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
        'NON-TECHNICAL',
        'ADDITIONAL EXERCISES',
      ],
      formLabel: 'PPC5',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 2 : -1,
            section: 1,
            subSection: 1,
            page: 1,
            posXList: [131, 190, 248],
            posYList: [84, 84, 84]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'FORREST GUMP' : '',
            section: 1,
            subSection: 1,
            // stringValue: 'Test',
            posX: 90,
            posY: 105),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s License No',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            section: 1,
            subSection: 1,
            fontSize: 8,
            // stringValue: 'TH.FCL.0009999',
            posX: 365,
            posY: 88),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? '0895' : '',
            section: 1,
            subSection: 1,
            keyboardType: TextInputType.number,
            maxLength: 4,
            // stringValue: '1234',
            posX: 385,
            posY: 104),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'Instructor\'s Rank',
            type: FieldType.radio,
            listValue: ['CAPT'],
            intValue: 0,
            stringValue: 'CAPT',
            editable: false,
            section: 1,
            subSection: 2,
            page: 1,
            posXList: [131],
            posYList: [118]),
        Field(
            name: 'instructor_name',
            label: 'Instructor\'s Name',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            section: 1,
            subSection: 2,
            // stringValue: 'Audrey H.',
            posX: 90,
            posY: 139),
        Field(
            name: 'instructor_cert_no',
            label: 'Ins Certificate No',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS-007' : '',
            posX: 367,
            posY: 122),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? '9999' : '',
            section: 1,
            subSection: 2,
            keyboardType: TextInputType.number,
            maxLength: 4,
            // stringValue: '1123',
            posX: 385,
            posY: 138),

        ///.....................................................................
        ///Examiner
        ///.....................................................................
        Field(
            name: 'examiner_type',
            label: 'Examiner\'s Type',
            type: FieldType.radio,
            listValue: ['DCP', 'PCPS', 'CAAT'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 3,
            page: 1,
            posXList: [131, 190, 248],
            posYList: [152, 152, 152]),
        Field(
            name: 'examiner_name',
            label: 'Examiner\'s Name',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'JOHN CONNOR' : '',
            section: 1,
            subSection: 3,
            // stringValue: 'David G.',
            posX: 90,
            posY: 174),
        Field(
            name: 'examiner_pel_no',
            label: 'PEL / CA No',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'PEL-999' : '',
            section: 1,
            subSection: 3,
            // stringValue: 'PEL123',
            posX: 368,
            posY: 156),
        Field(
            name: 'examiner_id',
            label: 'Examiner\'s Staff No(xxxx)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? '0000' : '',
            section: 1,
            subSection: 3,
            keyboardType: TextInputType.number,
            maxLength: 4,
            // stringValue: '0055',
            posX: 385,
            posY: 173),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            page: 1,
            section: 2,
            subSection: 1,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 500,
            // fontSize: 8,
            posY: 87),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            // stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            section: 2,
            subSection: 1,
            // fontSize: 8,
            posX: 500,
            posY: 104),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            section: 2,
            subSection: 1,
            // fontSize: 8,
            posX: 500,
            posY: 139),
        Field(
            name: 'route',
            label: 'ROUTE (ICAO AIRPORT CODE e.g. VTBS-VTCC)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'VTBS-EGLL' : '',
            section: 2,
            subSection: 1,
            // fontSize: 8,
            posX: 500,
            posY: 122),
        Field(
            name: 'check_type',
            label: 'Type of Check',
            // type: FieldType.radio,
            type: FieldType.checkbox,
            listValue: [
              'PPC / SKILL TEST',
              'INSTRUMENT RATING',
              'PBN OPERATIONS',
              'RIGHT HAND SEAT',
            ],
            checkBoxValue: [true, true, true, false],
            isMandatory: false,
            editable: false,
            editableList: [false, false, false, true],
            // intValue: 0,
            section: 2,
            subSection: 2,
            page: 1,
            posXList: [-10, -10, -10, 458],
            posYList: [-10, -10, -10, 187]),
        Field(
            name: 'check_type_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'TRUE'),
        Field(
            name: 'check_type_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'TRUE'),
        Field(
            name: 'check_type_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'TRUE'),
        Field(
            name: 'check_type_3',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 2,
            subSection: 2,
            stringValue: 'FALSE'),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label:
                'Preflight Preparation / Cockpit inspection / Use of Checklist (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 254),
        Field(
            name: 'q2_detail',
            label: 'Abnormal Engine Start ..........',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'HOT START' : '',
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posX: 202,
            posY: 268),
        Field(
            name: 'q2',
            label: 'Engine Start / Abnormal Engine Start …/ After Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 268),
        Field(
            name: 'q3',
            label:
                'Taxiing in Compliance with ATC Instructions / Before Takeoff Check (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 282),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 254,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q4',
            label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 310),
        Field(
            name: 'q5',
            label: 'Gusty Wind / Cross Wind Takeoff',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 324),
        Field(
            name: 'q6',
            label:
                'Rejected Takeoff at a reasonable speed before reaching V1 (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 338),
        Field(
            name: 'q7',
            label: 'Takeoff with Simulated Engine Failure at V2 (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 352),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 310,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q8',
            label:
                'Steep Turns 45° Bank, 180° Turn / Turns with and without spoilers',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 380),
        Field(
            name: 'q9',
            label: 'SID - Standard Instrument Departure / RNAV SID',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 394),
        Field(
            name: 'q10',
            label:
                'STAR Standard Terminal Arrival Route / RNAV STAR / Holding Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 408),
        Field(
            name: 'q11_check',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.checkbox,
            listValue: [
              'Clean',
              'Landing Configuration',
            ],
            checkBoxValue: [defaultCheck, defaultCheck],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [179, 216],
            posY: 419),
        Field(
            name: 'q11_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q11_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q11',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 421),
        Field(
            name: 'q12',
            label: '3D Approach to DH/A of 200 feet or higher minima',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 435),
        Field(
            name: 'q13_check',
            label: '2D Approach ....... down to the MDH/A (*)',
            type: FieldType.checkbox,
            listValue: [
              'RNP-RNAV',
              'VOR',
              'LOC',
            ],
            checkBoxValue: [defaultCheck, defaultCheck, defaultCheck],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [119, 176, 209],
            posY: 447),
        Field(
            name: 'q13_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q13_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q13_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q13',
            label: '2D Approach ....... down to the MDH/A (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 449),
        Field(
            name: 'q14',
            label: 'Manual Fly with / without Flight Director (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 463),
        Field(
            name: 'q15',
            label: 'Manual Fly with One Engine Inoperative (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 477),
        Field(
            name: 'q16_check',
            label: 'Approach Maneuvering',
            type: FieldType.checkbox,
            listValue: [
              'Visual Circuit',
              'Circling Approach',
            ],
            checkBoxValue: [defaultCheck, defaultCheck],
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: [152, 214],
            posY: 488),
        Field(
            name: 'q16_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q16_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            stringValue: 'FALSE'),
        Field(
            name: 'q16',
            label: 'Approach Maneuvering',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 491),
        Field(
            name: 'q17',
            label: 'PBN Operations: Normal and Non-normal Procedure (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 504),
        Field(
            name: 'q18',
            label: 'IR CHECK: Instrument Departure / Arrival / Approach (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 518),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 380,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q19',
            label: 'Pressurization / Air Condition / Bleed',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 546),
        Field(
            name: 'q20',
            label: 'Pitot / Static',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 560),
        Field(
            name: 'q21',
            label: 'Fuel',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 574),
        Field(
            name: 'q22',
            label: 'Electrical',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 588),
        Field(
            name: 'q23',
            label: 'Hydraulic',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 601),
        Field(
            name: 'q24',
            label: 'Flight Control and Trim (Degradation of Flight Control)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 615),
        Field(
            name: 'q25',
            label: 'Anti-Icing / De-Icing system / Glare Shield Heating',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 629),
        Field(
            name: 'q26',
            label: 'Autopilot / Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 643),
        Field(
            name: 'q27',
            label: 'Radios / Navigation Equipment / Instruments / FMS',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 657),
        Field(
            name: 'q28',
            label: 'Landing Gear and Brakes',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 670),
        Field(
            name: 'q29',
            label: 'Slats and Flaps',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 684),
        Field(
            name: 'q30',
            label: 'Engine / APU',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 699),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 546,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q31',
            label: 'Fire Drills',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 727),
        Field(
            name: 'q32',
            label: 'Smoke Control and Removal',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 741),
        Field(
            name: 'q33',
            label: 'Engine Failures / Shutdown / Restart',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 755),
        Field(
            name: 'q34',
            label: 'Windshear at Takeoff / Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 1,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 769),
        Field(
            name: 'q35',
            label: 'Emergency Descent',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            // intValue: 5,
            // stringValue: 'N/O',
            // editable: false,
            page: 1,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 783),
        Field(
            name: 'q36',
            label: 'Pilot Incapacitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 97),
        Field(
            name: 'q37',
            label: 'TCAS event (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 111),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 727,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q38',
            label: 'Go Around / Missed Approach Procedure with all engines',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 139),
        Field(
            name: 'q39',
            label:
                'Go Around / Missed Approach Procedure with one engine failure (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 153),
        Field(
            name: 'q40',
            label: 'Rejected Landing below DH / MDH / After Touchdown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 167),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 139,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q41',
            label: 'Normal Landing (Obtain Visual at DA/H)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 195),
        Field(
            name: 'q42',
            label: 'Landing in Out-Of-Trim Position',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 208),
        Field(
            name: 'q43',
            label: 'Crosswind landings / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 222),
        Field(
            name: 'q44',
            label: 'Reduced Flaps Landing (Flap3 or less)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 236),
        Field(
            name: 'q45',
            label: 'Landing with Simulated Engine Failure (Critical Engine)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 250),
        Field(
            name: 'q46',
            label:
                'Landing Roll / After Landing / Parking / Securing Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 263),
        Field(
            name: 'q47',
            label: 'Pax Evacuation Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 278),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 195,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q48',
            label: 'Engine Failure before V1 RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 306),
        Field(
            name: 'q49',
            label: 'Engine Failure at Takeoff after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 320),
        Field(
            name: 'q50',
            label: 'One Engine inoperative ILS Approach Go-Around and Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 334),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 306,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q51',
            label:
                'Crew Resource Management (CRM) / Assertiveness / Support Process',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 361),
        Field(
            name: 'q52',
            label: 'Threat & Error Management / Security & Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 375),
        Field(
            name: 'q53',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 389),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 361,
            width: 115,
            fontSize: 8),

        ///---------
        Field(
            name: 'q54_detail',
            label: 'Additional Exercises 1',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 418),
        Field(
            name: 'q54',
            label: 'Additional Exercises 1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 417),
        Field(
            name: 'q55_detail',
            label: 'Additional Exercises 2',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 432),
        Field(
            name: 'q55',
            label: 'Additional Exercises 2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 431),
        Field(
            name: 'q56_detail',
            label: 'Additional Exercises 3',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 446),
        Field(
            name: 'q56',
            label: 'Additional Exercises 3',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 445),
        Field(
            name: 'q57_detail',
            label: 'Additional Exercises 4',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 460),
        Field(
            name: 'q57',
            label: 'Additional Exercises 4',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 459),
        Field(
            name: 'q58_detail',
            label: 'Additional Exercises 5',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 474),
        Field(
            name: 'q58',
            label: 'Additional Exercises 5',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 473),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 417,
            width: 115,
            fontSize: 8),

        ///---------

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 493),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 493),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 538),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 551),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 564),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 577),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 588),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 601),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 614),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 627),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 640),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 5,
            subSection: 1,
            // isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 543,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [138, 228, 339, 441, 504],
            posY: 668),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 100,
            sigMaxHeight: 60,
            page: 2,
            section: 7,
            posX: 75,
            posY: 745),
        Field(
            // name: 'PILOT_NAME',
            // label: 'Pilot Name',
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 770),
        Field(
            // name: 'pilot_sig_date',
            // label: 'Date',
            // keyboardType: TextInputType.datetime,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            page: 2,
            section: 7,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 780),
        Field(
            name: 'examiner_sig',
            label: 'Examiner\'s Signature',
            type: FieldType.signature,
            sigWidth: 100,
            sigMaxHeight: 60,
            page: 2,
            section: 7,
            posX: 245,
            posY: 745),
        Field(
            duplicateFrom: 'examiner_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 245,
            posY: 770),
        Field(
            // name: 'examiner_sig_date',
            // label: 'Date',
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            // keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 245,
            posY: 780),
        // Field(
        //     name: 'staff_name',
        //     isMandatory: false,
        //     input: false,
        //     type: FieldType.string,
        //     page: 2,
        //     section: 7,
        //     stringValue: 'JATUPATRA SUETRONG',
        //     posX: 420,
        //     posY: 770),
        // Field(
        //     name: 'staff_sig_date',
        //     duplicateFrom: 'check_date',
        //     label: 'Date',
        //     type: FieldType.date,
        //     keyboardType: TextInputType.datetime,
        //     input: false,
        //     page: 2,
        //     section: 7,
        //     stringValue:
        //         DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
        //     dateTimeValue: DateTime.now(),
        //     posX: 420,
        //     posY: 780),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Pilot info.
        'pilot_rank': form.getStrVal('pilot_rank'),
        'pilot_id': form.getStrVal('pilot_id'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_name': form.getStrVal('pilot_name'),

        //Instructor info.
        'instructor_rank': form.getStrVal('instructor_rank'),
        'instructor_id': form.getStrVal('instructor_id'),
        'instructor_cert_no': form.getStrVal('instructor_cert_no'),
        'instructor_name': form.getStrVal('instructor_name'),

        ///Examiner info.
        'examiner_type': form.getStrVal('examiner_type'),
        'examiner_id': form.getStrVal('examiner_id'),
        'examiner_pel_no': form.getStrVal('examiner_pel_no'),
        'examiner_name': form.getStrVal('examiner_name'),

        ///Check details
        'check_date': form.getStrVal('check_date'),
        'block_time': form.getStrVal('block_time'),
        'fstd_no': form.getStrVal('fstd_no'),
        'route': form.getStrVal('route'),
        'check_type_0': form.getStrVal('check_type_0'),
        'check_type_1': form.getStrVal('check_type_1'),
        'check_type_2': form.getStrVal('check_type_2'),
        'check_type_3': form.getStrVal('check_type_3'),

        ///Grading & Comment
        'q1': form.getStrVal('q1'),
        'q2_detail': form.getStrVal('q2_detail'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11_check_0': form.getStrVal('q11_check_0'),
        'q11_check_1': form.getStrVal('q11_check_1'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13_check_0': form.getStrVal('q13_check_0'),
        'q13_check_1': form.getStrVal('q13_check_1'),
        'q13_check_2': form.getStrVal('q13_check_2'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16_check_0': form.getStrVal('q16_check_0'),
        'q16_check_1': form.getStrVal('q16_check_1'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25': form.getStrVal('q25'),
        'q26': form.getStrVal('q26'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37': form.getStrVal('q37'),
        'q38': form.getStrVal('q38'),
        'q39': form.getStrVal('q39'),
        'q40': form.getStrVal('q40'),
        'q41': form.getStrVal('q41'),
        'q42': form.getStrVal('q42'),
        'q43': form.getStrVal('q43'),
        'q44': form.getStrVal('q44'),
        'q45': form.getStrVal('q45'),
        'q46': form.getStrVal('q46'),
        'q47': form.getStrVal('q47'),
        'q48': form.getStrVal('q48'),
        'q49': form.getStrVal('q49'),
        'q50': form.getStrVal('q50'),
        'q51': form.getStrVal('q51'),
        'q52': form.getStrVal('q52'),
        'q53': form.getStrVal('q53'),
        'q54_detail': form.getStrVal('q54_detail'),
        'q54': form.getStrVal('q54'),
        'q55_detail': form.getStrVal('q55_detail'),
        'q55': form.getStrVal('q55'),
        'q56_detail': form.getStrVal('q56_detail'),
        'q56': form.getStrVal('q56'),
        'q57_detail': form.getStrVal('q57_detail'),
        'q57': form.getStrVal('q57'),
        'q58_detail': form.getStrVal('q58_detail'),
        'q58': form.getStrVal('q58'),

        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qf_comment': form.getStrVal('qf_comment'),
        'qg_comment': form.getStrVal('qg_comment'),
        'qh_comment': form.getStrVal('qh_comment'),
        'qi_comment': form.getStrVal('qi_comment'),
        'qj_comment': form.getStrVal('qj_comment'),

        ///LANDING AND GO-AROUND
        'no_landing': form.getStrVal('no_landing'),
        'no_goaround': form.getStrVal('no_goaround'),

        ///COMPETENCY
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),
        //RESULT
        'result': form.getStrVal('result'),

        // 'pilot_sig_date': form.getStrVal('pilot_sig_date'),
        // 'examiner_sig_date': form.getStrVal('examiner_sig_date'),
      };
  }
}
