import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class PscForm {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<double> _gradePosX = [324, 339, 354, 370, 385, 400];
    int gradeCommentMaxLen = 250;
    int defaultGrade() => Authen.isTjo() ? 1 : -1;
    // bool defaultCheck = false;

    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training'
    //     ' as indicated, have supervised the required session in '
    //     'accordance with the published';

    return f.Form(
      type: f.FormType.psc,
      formName: 'PURSER UPGRADE',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: 'forms/psc.pdf',
      dbTable: kPscTable,
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Flight Detail',
        'Grading',
        'Additional Comment',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'PREFLIGHT BRIEFING',
        'PRE-DEPARTURE DUTIES',
        'BEFORE TAKEOFF ',
        'CRUISING',
        'FLIGHT DECK OBSERVATION',
        'AFTER LANDING',
        'DEBREIFING',
        'PA ANNOUCEMENT',
        'GENERAL KNOWLEDGE',
        'NON-TECHNICAL SKILLS',
      ],
      formLabel: 'PSC',
      formLabelInfoField1: 'trainee_id',
      formLabelInfoField2: 'trainee_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'trainee_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 115,
            posY: 102),
        Field(
            name: 'trainee_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 134,
            posY: 115),

        ///.....................................................................
        ///PURSER
        ///.....................................................................
        Field(
            name: 'purser_name',
            label: 'Purser\'s Name (Familiarization ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 265,
            posY: 102),
        Field(
            name: 'purser_id',
            label: 'Purser\'s Staff No(xxxx) (Familiarization ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            isMandatory: false,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 283,
            posY: 115),

        ///.....................................................................
        ///EVALUATOR
        ///.....................................................................
        Field(
            name: 'evaluator_name',
            label: 'Evaluator\'s Name (Checking ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 3,
            isMandatory: false,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 416,
            posY: 102),
        Field(
            name: 'evaluator_id',
            label: 'Evaluator\'s Staff No(xxxx) (Checking ONLY)',
            type: FieldType.string,
            section: 1,
            subSection: 3,
            maxLength: 4,
            isMandatory: false,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 433,
            posY: 115),

        ///.....................................................................
        ///FLIGHT DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 116,
            posY: 129),
        Field(
            name: 'check_course',
            label: 'Training Course',
            type: FieldType.radio,
            listValue: [
              'Initial Training ',
              'Conversion Training',
              'Requalification Training',
              'Senior Cabin Crew and Purser Upgrade',
            ],
            intValue: defaultGrade(),
            section: 2,
            posX: 46,
            posYList: [168, 182, 197, 212]),
        //---------------------------------------
        Field(
            name: 'check_type',
            label: 'TYPE OF TRAINING / CHECKING',
            type: FieldType.radio,
            listValue: [
              'Line Familiarization',
              'Line Checking',
            ],
            intValue: defaultGrade(),
            section: 2,
            subSection: 2,
            posX: 219,
            posYList: [168, 183]),
        //---------------------------------------
        Field(
            name: 'position',
            label: 'ASSIGNED POSITION (if applicable)',
            type: FieldType.radio,
            listValue: [
              'P2',
              'P3',
              'P4',
              'P5',
            ],
            intValue: defaultGrade(),
            isMandatory: false,
            section: 2,
            subSection: 3,
            posXList: [224, 268, 312, 355],
            posY: 212),
        //---------------------------------------
        Field(
            name: 'ac_type',
            label: 'A/C Type',
            type: FieldType.radio,
            listValue: [
              'A320',
              'A321',
              'B737',
            ],
            intValue: defaultGrade(),
            section: 2,
            subSection: 4,
            posXList: [448, 488, 528],
            posY: 168),
        Field(
            name: 'ac_reg',
            label: 'A/C Registration',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            stringValue: 'VK',
            posX: 462,
            posY: 217),
        Field(
            name: 'flight',
            label: 'Flight No.',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            posX: 457,
            posY: 186),
        Field(
            name: 'route',
            label: 'Route (DEP-DES)',
            type: FieldType.string,
            section: 2,
            subSection: 4,
            posX: 445,
            posY: 202),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label: 'On time performance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 264),
        Field(
            name: 'q2',
            label: 'Manner - Greeting among crew and office staffs',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 276),
        Field(
            name: 'q3',
            label: 'Make-up and grooming standard',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 287),
        Field(
            name: 'q4',
            label: 'Uniform and spare items',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 299),
        Field(
            name: 'q5',
            label: 'OMC / Roster cooperation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 311),
        Field(
            name: 'q6',
            label: 'Briefing Checklist preparation (readiness and completion)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 323),
        Field(
            name: 'q7',
            label: 'Self-introduction',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 335),
        Field(
            name: 'q8',
            label: 'Flight document & equipment',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 346),
        Field(
            name: 'q9',
            label: 'Complete flight information briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 358),
        Field(
            name: 'q10',
            label: 'Working position assignment',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 369),
        Field(
            name: 'q11',
            label: 'Safety briefing knowledge',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 380),
        Field(
            name: 'q12',
            label: 'New MTC and update company information',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 392),
        Field(
            name: 'q13',
            label: 'Communication with flight deck during briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 404),
        Field(
            name: 'q14',
            label: 'Time management during briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 416),
        Field(
            name: 'q15',
            label:
                'Briefing with flight crew - establishing of the daily password',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 427),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 265,
            width: 140,
            fontSize: 8),

        ///------------------------------------

        Field(
            name: 'q16',
            label: 'On time performance - Arriving at gate',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 451),
        Field(
            name: 'q17',
            label:
                'Manner - Personal and team grooming when present in public area',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 463),
        Field(
            name: 'q18',
            label:
                'Coordination with GS - Receiving of flight document and TOB',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 474),
        Field(
            name: 'q19',
            label: 'Relay information with team',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 486),
        Field(
            name: 'q20',
            label: 'Check Cabin Logbook & communication with team',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 498),
        Field(
            name: 'q21',
            label: 'Pre-flight safety & security check - cabin crew reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 509),
        Field(
            name: 'q22',
            label: 'Flight deck reporting of safety security checked',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 521),
        Field(
            name: 'q23',
            label: 'Flight deck serving on ground (water and rubbish bag)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 533),
        Field(
            name: 'q24',
            label: 'Check and receive of cabin readiness reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 545),
        Field(
            name: 'q25',
            label: 'Cabin preparation and cabin crew alerting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 556),
        Field(
            name: 'q26',
            label: 'Flight deck door policy - close before boarding',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 568),
        Field(
            name: 'q27',
            label: 'Inform GS ready for boarding',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 579),
        Field(
            name: 'q28',
            label:
                'Fight deck reporting: cabin ready and obtain boarding permission',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 591),
        Field(
            name: 'q29',
            label: 'Boarding performance: welcome, check boarding PAXs, etc.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 603),
        Field(
            name: 'q30',
            label:
                'PA while boarding - refueling, switch off electrical and mobile phone',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 615),
        Field(
            name: 'q31',
            label: 'Boarding complete procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 627),
        Field(
            name: 'q32',
            label: 'Headcount procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 639),
        Field(
            name: 'q33',
            label:
                'GS Coordination - Receive & confirm (Flight document and final TOB)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 650),
        Field(
            name: 'q34',
            label:
                'Flight deck reporting: check TOB & obtain door closing permission',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 662),
        Field(
            name: 'q35',
            label: 'Flight deck door policy - ensure flight deck door closed',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 673),
        Field(
            name: 'q36',
            label: 'Security check before closing main door',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 685),
        Field(
            name: 'q37',
            label: 'Door closing procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 709),
        Field(
            name: 'q38',
            label:
                'Ensure steps / aerobridge is removed from the aircraft door',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 720),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 453,
            width: 140,
            fontSize: 8),

        ///------------------------------------

        Field(
            name: 'q39',
            label: 'Arming procedure and reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 743),
        Field(
            name: 'q40',
            label: 'Welcome passengers - establish via PA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 755),
        Field(
            name: 'q41',
            label:
                'Safety Demonstration announcement and emergency exit briefing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 767),
        Field(
            name: 'q42',
            label: 'Cabin & galley preparation - before T/O PA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 88),
        Field(
            name: 'q43',
            label: 'Final cabin checking',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            page: 2,
            posXList: _gradePosX,
            posY: 100),
        Field(
            name: 'q44',
            label: 'Cabin readiness - receiving and reporting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            page: 2,
            posXList: _gradePosX,
            posY: 112),
        Field(
            name: 'q45',
            label: 'Correct BRACE position at take-off station',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            page: 2,
            posXList: _gradePosX,
            posY: 123),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 414,
            posY: 744,
            width: 140,
            fontSize: 8),

        ///------------------------------------

        Field(
            name: 'q46',
            label: 'Cabin preparation - after T/O announcement, etc.',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 147),
        Field(
            name: 'q47',
            label: 'Flight deck communication - Initiation and engagement',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 159),
        Field(
            name: 'q48',
            label: 'Service management',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 170),
        Field(
            name: 'q49',
            label: 'Distribution of ED card, sky boss service, PMB',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 182),
        Field(
            name: 'q50',
            label: 'Service Approach and Sales Skills',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 194),
        Field(
            name: 'q51',
            label: 'Cabin cleanliness includes rubbish collection',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 205),
        Field(
            name: 'q52',
            label: 'F&B, Merchandise, Duty free sales',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 217),
        Field(
            name: 'q53',
            label: 'Cabin surveillance - cabin and lavatory check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 229),
        Field(
            name: 'q54',
            label: 'Turbulence compliance procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 240),
        Field(
            name: 'q55',
            label: 'After service procedure - cabin lighting adjustment',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            page: 2,
            posXList: _gradePosX,
            posY: 252),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 149,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q56',
            label: 'Flight deck entry procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            page: 2,
            posXList: _gradePosX,
            posY: 275),
        Field(
            name: 'q57',
            label: 'Flight deck exit procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            page: 2,
            posXList: _gradePosX,
            posY: 287),
        Field(
            name: 'q58',
            label: 'Flight deck observer seat operation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            page: 2,
            posXList: _gradePosX,
            posY: 299),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 276,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q59',
            label: 'Landing procedure - Farewell PA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 322),
        Field(
            name: 'q60',
            label: 'Landing procedure - In-flight music',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 334),
        Field(
            name: 'q61',
            label: 'Disarming procedure and receive report',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 346),
        Field(
            name: 'q62',
            label: 'Door opening procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 357),
        Field(
            name: 'q63',
            label:
                'Step / aerobridge safety check before passenger disembarkation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 368),
        Field(
            name: 'q64',
            label:
                'Coordinate with GS - handover document, special information',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 380),
        Field(
            name: 'q65',
            label: 'Disembarkation position and farewell',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 392),
        Field(
            name: 'q66',
            label: 'Special passenger handling (INF, WCHR)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 404),
        Field(
            name: 'q67',
            label: 'Signaling with GS during disembarkation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 415),
        Field(
            name: 'q68',
            label: 'Security checking and receive report',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 427),
        Field(
            name: 'q69',
            label: 'Cabin cleanliness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 439),
        Field(
            name: 'q70',
            label: 'Transit duties',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            page: 2,
            posXList: _gradePosX,
            posY: 451),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 323,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q71',
            label:
                'De-briefing skills (coaching, leadership skill and comment)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            page: 2,
            posXList: _gradePosX,
            posY: 474),
        Field(
            name: 'q72',
            label: 'Target Achievement',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            page: 2,
            posXList: _gradePosX,
            posY: 486),
        Field(
            name: 'q73',
            label: 'Grooming maintain ability',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            page: 2,
            posXList: _gradePosX,
            posY: 498),
        Field(
            name: 'q74',
            label: 'VR report',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 7,
            gradeSection: 7,
            page: 2,
            posXList: _gradePosX,
            posY: 509),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 476,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q75',
            label: 'Correctness and pronunciation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 8,
            gradeSection: 8,
            page: 2,
            posXList: _gradePosX,
            posY: 533),
        Field(
            name: 'q76',
            label: 'Speed control & phrasing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 8,
            gradeSection: 8,
            page: 2,
            posXList: _gradePosX,
            posY: 544),
        Field(
            name: 'q77',
            label: 'Tone & intonation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 8,
            gradeSection: 8,
            page: 2,
            posXList: _gradePosX,
            posY: 556),
        Field(
            name: 'q78',
            label: 'Appropriate time management',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 8,
            gradeSection: 8,
            page: 2,
            posXList: _gradePosX,
            posY: 568),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 534,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q79',
            label: 'Flight Time Limitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 591),
        Field(
            name: 'q80',
            label: 'Rest period requirement',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 603),
        Field(
            name: 'q81',
            label: 'Handling of disruptive / abusive passenger',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 614),
        Field(
            name: 'q82',
            label: 'Stowage of cabin baggage',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 626),
        Field(
            name: 'q83',
            label: 'Portable Electronic Devices (PED)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 638),
        Field(
            name: 'q84',
            label: 'Medical case on board procedure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 650),
        Field(
            name: 'q85',
            label: 'Document and form',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 661),
        Field(
            name: 'q86',
            label: 'Irregularity case report channel',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 9,
            gradeSection: 9,
            page: 2,
            posXList: _gradePosX,
            posY: 673),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 592,
            width: 140,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q87',
            label: 'Working attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 697),
        Field(
            name: 'q88',
            label: 'Leadership',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 708),
        Field(
            name: 'q89',
            label: 'Time management',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 720),
        Field(
            name: 'q90',
            label: 'Teamwork',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 732),
        Field(
            name: 'q91',
            label: 'Problem solving',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 743),
        Field(
            name: 'q92',
            label: 'Safety and security awareness',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 754),
        Field(
            name: 'q93',
            label: 'Communication',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 10,
            gradeSection: 10,
            page: 2,
            posXList: _gradePosX,
            posY: 767),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            page: 2,
            posX: 414,
            posY: 697,
            width: 140,
            fontSize: 8),

        ///.....................................................................
        ///ADDITIONAL COMMENT
        ///.....................................................................
        Field(
            name: 'additional_comment',
            label: 'Additional Comment (if applicable)',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 3,
            section: 4,
            subSection: 1,
            // isMandatory: false,
            maxLength: 2000,
            posX: 42,
            posY: 98,
            width: 500,
            height: 500,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 3,
            section: 5,
            subSection: 1,
            posXList: [138, 227, 339, 441, 505],
            posY: 381),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'trainee_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 3,
            section: 6,
            posX: 75,
            posY: 501),
        Field(
            duplicateFrom: 'trainee_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 3,
            section: 6,
            posX: 70,
            posY: 524),
        Field(
            name: 'trainee_sig_date',
            label: 'Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 3,
            section: 6,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 539),

        ///------------------------------------
        Field(
            name: 'purser_sig',
            label: 'Purser\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 3,
            section: 6,
            subSection: 2,
            posX: 205,
            posY: 501),
        Field(
            duplicateFrom: 'purser_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 3,
            section: 6,
            posX: 200,
            posY: 524),
        Field(
            name: 'purser_sig_date',
            label: 'Date',
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 3,
            section: 6,
            subSection: 2,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 200,
            posY: 539),

        ///------------------------------------
        Field(
            name: 'evaluator_sig',
            label: 'Evaluator\'s Signature (Only for check flight)',
            type: FieldType.signature,
            isMandatory: false,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 3,
            section: 6,
            subSection: 3,
            posX: 335,
            posY: 501),
        Field(
            duplicateFrom: 'evaluator_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 3,
            section: 6,
            posX: 330,
            posY: 524),
        Field(
            name: 'evaluator_result',
            label: 'Result',
            type: FieldType.radio,
            isMandatory: false,
            listValue: ['PASS', 'FAIL'],
            intValue: defaultGrade(),
            page: 3,
            section: 6,
            subSection: 3,
            posXList: [321, 383],
            posY: 444),
        Field(
            name: 'evaluator_sig_date',
            label: 'Date (Only for check flight)',
            isMandatory: false,
            type: FieldType.date,
            keyboardType: TextInputType.datetime,
            page: 3,
            section: 6,
            subSection: 3,
            stringValue: '                  ',
            // DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 330,
            posY: 539),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Trainee info.
        'trainee_name': form.getStrVal('trainee_name'),
        'trainee_id': form.getStrVal('trainee_id'),

        ///Purser info.
        'purser_name': form.getStrVal('purser_name'),
        'purser_id': form.getStrVal('purser_id'),

        ///Evaluator
        'evaluator_name': form.getStrVal('evaluator_name'),
        'evaluator_id': form.getStrVal('evaluator_id'),

        ///Flight details
        'check_date': form.getStrVal('check_date'),
        'check_course': form.getStrVal('check_course'),
        'check_type': form.getStrVal('check_type'),
        'position': form.getStrVal('position'),
        'ac_type': form.getStrVal('ac_type'),
        'ac_reg': form.getStrVal('ac_reg'),
        'flight': form.getStrVal('flight'),
        'route': form.getStrVal('route'),

        ///Grading & Comment
        'q1': form.getStrVal('q1'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25': form.getStrVal('q25'),
        'q26': form.getStrVal('q26'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37': form.getStrVal('q37'),
        'q38': form.getStrVal('q38'),
        'q39': form.getStrVal('q39'),
        'q40': form.getStrVal('q40'),
        'q41': form.getStrVal('q41'),
        'q42': form.getStrVal('q42'),
        'q43': form.getStrVal('q43'),
        'q44': form.getStrVal('q44'),
        'q45': form.getStrVal('q45'),
        'q46': form.getStrVal('q46'),
        'q47': form.getStrVal('q47'),
        'q48': form.getStrVal('q48'),
        'q49': form.getStrVal('q49'),
        'q50': form.getStrVal('q50'),
        'q51': form.getStrVal('q51'),
        'q52': form.getStrVal('q52'),
        'q53': form.getStrVal('q53'),
        'q54': form.getStrVal('q54'),
        'q55': form.getStrVal('q55'),
        'q56': form.getStrVal('q56'),
        'q57': form.getStrVal('q57'),
        'q58': form.getStrVal('q58'),
        'q59': form.getStrVal('q59'),
        'q60': form.getStrVal('q60'),
        'q61': form.getStrVal('q61'),
        'q62': form.getStrVal('q62'),
        'q63': form.getStrVal('q63'),
        'q64': form.getStrVal('q64'),
        'q65': form.getStrVal('q65'),
        'q66': form.getStrVal('q66'),
        'q67': form.getStrVal('q67'),
        'q68': form.getStrVal('q68'),
        'q69': form.getStrVal('q69'),
        'q70': form.getStrVal('q70'),
        'q71': form.getStrVal('q71'),
        'q72': form.getStrVal('q72'),
        'q73': form.getStrVal('q73'),
        'q74': form.getStrVal('q74'),
        'q75': form.getStrVal('q75'),
        'q76': form.getStrVal('q76'),
        'q77': form.getStrVal('q77'),
        'q78': form.getStrVal('q78'),
        'q79': form.getStrVal('q79'),
        'q80': form.getStrVal('q80'),
        'q81': form.getStrVal('q81'),
        'q82': form.getStrVal('q82'),
        'q83': form.getStrVal('q83'),
        'q84': form.getStrVal('q84'),
        'q85': form.getStrVal('q85'),
        'q86': form.getStrVal('q86'),
        'q87': form.getStrVal('q87'),
        'q88': form.getStrVal('q88'),
        'q89': form.getStrVal('q89'),
        'q90': form.getStrVal('q90'),
        'q91': form.getStrVal('q91'),
        'q92': form.getStrVal('q92'),
        'q93': form.getStrVal('q93'),

        ///GRADING COMMENTS
        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qf_comment': form.getStrVal('qf_comment'),
        'qg_comment': form.getStrVal('qg_comment'),
        'qh_comment': form.getStrVal('qh_comment'),
        'qi_comment': form.getStrVal('qi_comment'),
        'qj_comment': form.getStrVal('qj_comment'),

        ///Additional Comment
        'additional_comment': form.getStrVal('additional_comment'),

        ///RESULT
        'result': form.getStrVal('result'),
        'evaluator_result': form.getStrVal('evaluator_result'),
        'trainee_sig_date': form.getStrVal('trainee_sig_date'),
        'purser_sig_date': form.getStrVal('purser_sig_date'),
        'evaluator_sig_date': form.getStrVal('evaluator_sig_date'),
      };
  }
}
