import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class Rt1Form {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;
    String defaultComment = '';

    String formName() => DateTime.now().isAfter(kFirstMay25)
        ? 'forms/rt11.pdf'
        : 'forms/rt10.pdf';
    String rtQ35text() => DateTime.now().isAfter(kFirstMay25)
        ? 'Unreliable Airspeed Indication / ALL ADR OFF procedure'
        : 'Pax Evacuation Procedures';
    // 'I am being a person authorized by TVJ and/or CAAT to conduct such training'
    // ' as indicated, have supervised the required session in '
    // 'accordance with the published';
    // int defaultGrade() => Authen.isTjo() ? -1 : -1;
    // bool defaultCheck = true;

    return f.Form(
      type: f.FormType.rt1,
      formName: 'RT1',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName(),
      dbTable: kRt1Table,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'DISCUSSION - PERFORMANCE',
        'PREFLIGHT PREPARATION AND GROUND OPERATIONS',
        'TAKEOFF',
        'INFLIGHT MANEUVERS AND PROCEDURES',
        'AIRCRAFT SYSTEM MALFUNCTION',
        'ABNORMAL AND EMERGENCY PROCEDURE',
        'MISSED APPROACH PROCEDURES',
        'LANDINGS AND AFTER LANDING PROCEDURES',
        'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
        'NON-TECHNICAL',
        'ADDITIONAL EXERCISES / OTHERS',
      ],
      formLabel: 'RT1',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [132, 218, 218],
            posYList: [84, 84, 84]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 106),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s License No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 365,
            posY: 88),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 386,
            posY: 105),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'Instructor\'s Rank',
            type: FieldType.radio,
            listValue: ['CAPT'],
            intValue: 0,
            stringValue: 'CAPT',
            editable: false,
            section: 1,
            subSection: 2,
            posXList: [131],
            posYList: [117]),
        Field(
            name: 'instructor_name',
            label: 'Instructor\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 140),
        Field(
            name: 'instructor_cert_no',
            label: 'INS / IC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 368,
            posY: 123),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 386,
            posY: 138),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 498,
            posY: 88),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
            // stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            posX: 498,
            posY: 105),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 498,
            posY: 140),
        Field(
            name: 'loft_duty',
            label: 'LOFT Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [501, 528],
            posYList: [153, 153]),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label: 'Environment: Adverse Weather / Cold Weather Operations',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 225),
        Field(
            name: 'q2',
            label: 'Emergency Descent / Diversion Strategy',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 239),
        Field(
            name: 'q3',
            label: 'Windshear Prediction / Reaction',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 253),
        Field(
            name: 'q4',
            label:
                'Threat and Error Management (TEM) / Pilot Competencies / Building Resilience',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 266),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 225,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q5',
            label:
                'Preflight Preparation / Briefing using TEM CARD / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 294),
        Field(
            name: 'q6_detail',
            label: 'Abnormal Engine Start …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: Authen.isTjo() ? 'HOT START' : '',
            posX: 200,
            posY: 308),
        Field(
            name: 'q6',
            label:
                'Engine Start / Abnormal Engine Start …………………………. / After Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 308),
        Field(
            name: 'q7',
            label:
                'Taxi Technique / Assistance / ATC Compliance / Before Takeoff Check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 322),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 294,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q8',
            label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 350),
        Field(
            name: 'q9',
            label: 'Gusty Wind / Cross Wind Takeoff',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 364),
        Field(
            name: 'q10',
            label: 'Takeoff: Engine Failure / Fire before V1 - RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 378),
        Field(
            name: 'q11',
            label: 'Takeoff: Engine Failure / Fire after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 391),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 350,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q12',
            label: 'SID - Standard Instrument Departure / RNAV SID',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 419),
        Field(
            name: 'q13',
            label:
                'STAR Standard Terminal Arrival Route / RNAV STAR / Holding Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 433),
        Field(
            name: 'q14',
            label: 'PBN Operations: Normal and Non-normal Procedure (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 447),
        Field(
            name: 'q15',
            label: 'Procedures For Loss of RNP Capability',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 461),
        Field(
            name: 'q16',
            label:
                'Approach Preparation / Briefing using TEM CARD / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 475),
        Field(
            name: 'q17',
            label: 'Descent and Approach Management / Aircraft Configuration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 488),
        Field(
            name: 'q18',
            label: 'Stabilized Approach Criteria and Compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 502),
        Field(
            name: 'q19',
            label: '3D Approach to DH/A of 200 Feet or Higher',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 516),
        Field(
            name: 'q20_check',
            label: '2D Approach ..........  down to the MDH/A',
            type: FieldType.checkbox,
            listValue: [
              'RNP-RNAV',
              'VOR',
              'LOC',
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [118, 176, 210],
            posY: 528),
        Field(
            name: 'q20_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q20_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q20_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q20',
            label: '2D Approach',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 530),
        Field(
            name: 'q21_check',
            label: 'Approach Maneuvering',
            type: FieldType.checkbox,
            listValue: [
              'Visual Circuit',
              'Circling Approach',
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [155, 217],
            posY: 543),
        Field(
            name: 'q21_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q21_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q21',
            label: 'Approach Maneuvering',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 544),
        Field(
            name: 'q22',
            label: 'Manual Fly with / without Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 557),
        Field(
            name: 'q23',
            label: 'Manual Fly with One Engine Inoperative',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 572),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 419,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q24',
            label: 'Air Condition / Pressurization / Ventilation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 600),
        Field(
            name: 'q25',
            label: 'Fire Protection',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 613),
        Field(
            name: 'q26',
            label: 'Navigation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX,
            posY: 628),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 600,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q27',
            label: 'Engine Fire Handling and Decision Making',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 656),
        Field(
            name: 'q28',
            label: 'Engine Failures / Shutdown / Restart',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 670),
        Field(
            name: 'q29',
            label: 'Windshear at Takeoff / Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 683),
        Field(
            name: 'q30',
            label: 'Emergency Descent / Diversion Strategy',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 697),
        Field(
            name: 'q31',
            label: 'Pilot Incapacitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 711),
        Field(
            name: 'q32',
            label: 'TCAS TA Response (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 725),
        Field(
            name: 'q33',
            label:
                'TCAS RA - Initial RAs that require a change in vertical speed (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 738),
        Field(
            name: 'q34',
            label: 'Declaration of Emergency or Urgency',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 752),
        Field(
            name: 'q35',
            label: rtQ35text(),
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 766),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 656,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q36',
            label: 'Go Around / Missed Approach Procedure with all engines',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 111),
        Field(
            name: 'q37',
            label:
                'Go Around / Missed Approach Procedure with one engine failure (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 125),
        Field(
            name: 'q38',
            label: 'Rejected Landing below DH / MDH / After Touchdown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 139),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 111,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q39',
            label: 'Normal Landing / Landing Technique / Landing Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 167),
        Field(
            name: 'q40',
            label: 'Crosswind landings / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 181),
        Field(
            name: 'q41',
            label: 'Reduced Flaps Landing (Flap3 or less)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 195),
        Field(
            name: 'q42',
            label: 'Landing with Simulated Engine Failure (Critical Engine)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 209),
        Field(
            name: 'q43',
            label:
                'Landing Roll / After Landing / Parking / Securing Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 222),
        Field(
            name: 'q44',
            label: 'Pax Evacuation Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 236),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 167,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q45',
            label: 'Engine Failure before V1 RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 264),
        Field(
            name: 'q46',
            label: 'Engine Failure at Takeoff after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 278),
        Field(
            name: 'q47',
            label: 'One Engine inoperative ILS Approach Go-Around and Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 291),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 264,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q48',
            label:
                'Crew Resource Management (CRM) / Assertiveness / Support Process',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 320),
        Field(
            name: 'q49',
            label: 'Threat & Error Management / Security & Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 334),
        Field(
            name: 'q50',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 347),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            // isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 320,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q51',
            label:
                'Green Operations Policy (One Engine Taxi / Reduced Flaps Landing)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 377),
        Field(
            name: 'q52_detail',
            label: 'Additional Exercises 1',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 391),
        Field(
            name: 'q52',
            label: 'Additional Exercises 1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 389),
        Field(
            name: 'q53_detail',
            label: 'Additional Exercises 2',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 405),
        Field(
            name: 'q53',
            label: 'Additional Exercises 2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 403),
        Field(
            name: 'q54_detail',
            label: 'Additional Exercises 3',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 419),
        Field(
            name: 'q54',
            label: 'Additional Exercises 3',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 417),
        Field(
            name: 'q55_detail',
            label: 'Additional Exercises 4',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 431),
        Field(
            name: 'q55',
            label: 'Additional Exercises 4',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 430),
        Field(
            name: 'qk_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 377,
            width: 115,
            fontSize: 8),

        ///------------------------------------

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 456),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 456),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 506),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 519),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 532),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 543),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 556),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 569),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 582),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 595),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 608),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 5,
            subSection: 1,
            // isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 508,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [138, 228, 339, 440, 504],
            posY: 635),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 75,
            posY: 728),
        Field(
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 754),
        Field(
            // name: 'pilot_sig_date',
            // label: 'Date',
            type: FieldType.date,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            // keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            // dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 764),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 245,
            posY: 728),
        Field(
            duplicateFrom: 'instructor_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 245,
            posY: 754),
        Field(
            // name: 'instructor_sig_date',
            // label: 'Date',
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
            // keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
            // stringValue:
            //     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 245,
            posY: 764),
        // Field(
        //     name: 'staff_name',
        //     isMandatory: false,
        //     input: false,
        //     type: FieldType.string,
        //     page: 2,
        //     section: 7,
        //     stringValue: 'JATUPATRA SUETRONG',
        //     posX: 420,
        //     posY: 754),
        // Field(
        //     name: 'staff_sig_date',
        //     duplicateFrom: 'check_date',
        //     label: 'Date',
        //     type: FieldType.date,
        //     keyboardType: TextInputType.datetime,
        //     input: false,
        //     page: 2,
        //     section: 7,
        //     stringValue:
        //         DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
        //     dateTimeValue: DateTime.now(),
        //     posX: 420,
        //     posY: 764),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Pilot info.
        'pilot_rank': form.getStrVal('pilot_rank'),
        'pilot_name': form.getStrVal('pilot_name'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_id': form.getStrVal('pilot_id'),

        ///Instructor info.
        'instructor_rank': form.getStrVal('instructor_rank'),
        'instructor_name': form.getStrVal('instructor_name'),
        'instructor_cert_no': form.getStrVal('instructor_cert_no'),
        'instructor_id': form.getStrVal('instructor_id'),

        ///Check details
        'check_date': form.getStrVal('check_date'),
        'block_time': form.getStrVal('block_time'),
        'fstd_no': form.getStrVal('fstd_no'),
        'loft_duty': form.getStrVal('loft_duty'),

        ///Grading & Comment
        ///A
        'q1': form.getStrVal('q1'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5': form.getStrVal('q5'),
        'q6_detail': form.getStrVal('q6_detail'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20_check_0': form.getStrVal('q20_check_0'),
        'q20_check_1': form.getStrVal('q20_check_1'),
        'q20_check_2': form.getStrVal('q20_check_2'),
        'q20': form.getStrVal('q20'),
        'q21_check_0': form.getStrVal('q21_check_0'),
        'q21_check_1': form.getStrVal('q21_check_1'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25': form.getStrVal('q25'),
        'q26': form.getStrVal('q26'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37': form.getStrVal('q37'),
        'q38': form.getStrVal('q38'),
        'q39': form.getStrVal('q39'),
        'q40': form.getStrVal('q40'),
        'q41': form.getStrVal('q41'),
        'q42': form.getStrVal('q42'),
        'q43': form.getStrVal('q43'),
        'q44': form.getStrVal('q44'),
        'q45': form.getStrVal('q45'),
        'q46': form.getStrVal('q46'),
        'q47': form.getStrVal('q47'),
        'q48': form.getStrVal('q48'),
        'q49': form.getStrVal('q49'),
        'q50': form.getStrVal('q50'),
        'q51': form.getStrVal('q51'),
        'q52_detail': form.getStrVal('q52_detail'),
        'q52': form.getStrVal('q52'),
        'q53_detail': form.getStrVal('q53_detail'),
        'q53': form.getStrVal('q53'),
        'q54_detail': form.getStrVal('q54_detail'),
        'q54': form.getStrVal('q54'),
        'q55_detail': form.getStrVal('q55_detail'),
        'q55': form.getStrVal('q55'),

        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qg_comment': form.getStrVal('qg_comment'),
        'qh_comment': form.getStrVal('qh_comment'),
        'qi_comment': form.getStrVal('qi_comment'),
        'qj_comment': form.getStrVal('qj_comment'),
        'qk_comment': form.getStrVal('qk_comment'),

        ///LANDING AND GO-AROUND
        'no_landing': form.getStrVal('no_landing'),
        'no_goaround': form.getStrVal('no_goaround'),

        ///COMPETENCY
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),

        ///RESULT
        'result': form.getStrVal('result'),
        // 'pilot_sig_date': form.getStrVal('pilot_sig_date'),
        // 'instructor_sig_date': form.getStrVal('instructor_sig_date'),
      };
  }
}
