import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import 'package:marverick/models/form.dart' as f;
import 'package:marverick/models/field.dart';
import 'package:marverick/services/authen.dart';
import 'package:marverick/utils/constants.dart';

class Rt4Form {
  static final uuid = Uuid();

  static f.Form init() {
    DateTime timeStamp = DateTime.now();

    List<String> _gradeList = ['1', '2', '3', '4', '5', 'N/O'];
    List<String> _gradeList2 = ['1', '2', '3', '4', '5'];
    List<double> _gradePosX = [360, 375, 389, 403, 417, 432];
    List<double> _gradePosX2 = [360, 375, 389, 403, 417];
    int gradeCommentMaxLen = 400;
    int defaultGrade() => Authen.isTjo() ? 2 : -1;
    bool defaultCheck = false;

    String formName = 'forms/rt4.pdf';
    String defaultComment = '';
    // String defaultComment =
    //     'I am being a person authorized by TVJ and/or CAAT to conduct such training as indicated, have supervised the required session in accordance with the published';
    // int defaultGrade() => Authen.isTjo() ? -1 : -1;
    // bool defaultCheck = true;

    return f.Form(
      type: f.FormType.rt4,
      formName: 'RT4',
      createDateTime: timeStamp,
      createBy: Authen.user != null ? Authen.user.email : '',
      id: uuid.v1(),
      filePath: formName,
      dbTable: kRt4Table,
      dateFormat: 'dd MMM yyyy',
      fontSize: 8,
      sectionLabel: [
        'Personal Detail',
        'Check Detail',
        'Grading',
        'Number of Manual Landing and Go-around',
        'Competency Assessment and Comments',
        'Result',
        'Signature',
      ],
      gradeSectionLabel: [
        'DISCUSSION - PERFORMANCE',
        'PREFLIGHT PREPARATION AND GROUND OPERATIONS',
        'TAKEOFF',
        'INFLIGHT MANEUVERS AND PROCEDURES',
        'AIRCRAFT SYSTEM MALFUNCTION',
        'ABNORMAL AND EMERGENCY PROCEDURE',
        'MISSED APPROACH PROCEDURES',
        'LANDINGS AND AFTER LANDING PROCEDURES',
        'RIGHT HAND SEAT PROFICIENCY (for RHS Captains only))',
        'NON-TECHNICAL',
        'ADDITIONAL EXERCISES / OTHERS',
      ],
      formLabel: 'RT4',
      formLabelInfoField1: 'pilot_rank',
      formLabelInfoField2: 'pilot_name',
      fields: [
        ///.....................................................................
        ///TRAINEE
        ///.....................................................................
        Field(
            name: 'pilot_rank',
            label: 'Trainee\'s Rank',
            type: FieldType.radio,
            listValue: ['Capt.', 'SFO.', 'FO.'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 1,
            subSection: 1,
            posXList: [132, 219, 219],
            posYList: [84, 84, 84]),
        Field(
            name: 'pilot_name',
            label: 'Trainee\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TEERACHART JO.' : '',
            posX: 80,
            posY: 106),
        Field(
            name: 'pilot_license_no',
            label: 'Trainee\'s FCL No',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            stringValue: Authen.isTjo() ? 'TH.FCL.9999999' : '',
            posX: 365,
            posY: 88),
        Field(
            name: 'pilot_id',
            label: 'Trainee\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 1,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '0895' : '',
            posX: 386,
            posY: 105),

        ///.....................................................................
        ///INSTRUCTOR
        ///.....................................................................
        Field(
            name: 'instructor_rank',
            label: 'SFI\'s Rank',
            type: FieldType.radio,
            listValue: ['CAPT'],
            stringValue: 'CAPT',
            intValue: 0,
            editable: false,
            section: 1,
            subSection: 2,
            posXList: [132],
            posYList: [117]),
        Field(
            name: 'instructor_name',
            label: 'SFI\'s Name',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'MAVERICK' : '',
            posX: 80,
            posY: 140),
        Field(
            name: 'instructor_cert_no',
            label: 'FIC No.',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            stringValue: Authen.isTjo() ? 'INS MAV' : '',
            posX: 368,
            posY: 122),
        Field(
            name: 'instructor_id',
            label: 'Instructor\'s Staff No(xxxx)',
            type: FieldType.string,
            section: 1,
            subSection: 2,
            maxLength: 4,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '9999' : '',
            posX: 386,
            posY: 139),

        ///.....................................................................
        ///CHECK DETAILS
        ///.....................................................................
        Field(
            name: 'check_date',
            label: 'Date',
            // type: FieldType.string,
            type: FieldType.date,
            section: 2,
            keyboardType: TextInputType.datetime,
            stringValue:
                DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 493,
            posY: 88),
        Field(
            name: 'block_time',
            label: 'Block Time',
            type: FieldType.string,
            section: 2,
            // stringValue: Authen.isTjo() ? '04:00' : '',
            stringValue: '04:00',
            posX: 493,
            posY: 105),
        Field(
            name: 'fstd_no',
            label: 'FSTD No.',
            type: FieldType.string,
            section: 2,
            stringValue: Authen.isTjo() ? 'FSTD-999' : '',
            posX: 493,
            posY: 122),
        Field(
            name: 'ac_type',
            label: 'ACFT Type',
            type: FieldType.radio,
            listValue: ['A320', 'B737'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 527],
            posYList: [135, 135]),
        Field(
            name: 'route',
            label: 'Route (ICAO AIRPORT CODE e.g. VTBS-VTCC)',
            type: FieldType.string,
            stringValue: Authen.isTjo() ? 'VTBS-RCTP' : '',
            section: 2,
            posX: 368,
            posY: 157),
        Field(
            name: 'rhs',
            label: 'RHS',
            type: FieldType.radio,
            listValue: ['Yes', 'No'],
            intValue: Authen.isTjo() ? 0 : -1,
            section: 2,
            posXList: [219, 1000],
            posYList: [152, 1000]),
        Field(
            name: 'loft_duty',
            label: 'LOFT Duty',
            type: FieldType.radio,
            listValue: ['PF', 'PM'],
            intValue: Authen.isTjo() ? 1 : -1,
            section: 2,
            posXList: [492, 520],
            posYList: [152, 152]),

        ///.....................................................................
        ///GRADING
        ///.....................................................................
        Field(
            name: 'q1',
            label:
                'Adverse Weather / Runway Contamination / Thunderstorm Avoidance*',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 223),
        Field(
            name: 'q2',
            label: 'Emergency: RTO / EMER DES / CREW INCAP / EMER EVAC',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 237),
        Field(
            name: 'q3',
            label: 'Glide Slope Interception from Above',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 1,
            gradeSection: 1,
            posXList: _gradePosX,
            posY: 250),
        Field(
            name: 'qa_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 1,
            gradeSection: 1,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 224,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q4',
            label: 'Preflight Preparation / Briefing / TEM / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 278),
        Field(
            name: 'q5_detail',
            label: 'Abnormal Engine Start …………………………',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            stringValue: Authen.isTjo() ? 'HOT START' : '',
            posX: 200,
            posY: 292),
        Field(
            name: 'q5',
            label:
                'Engine Start / Abnormal Engine Start …………………………. / After Start',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 292),
        Field(
            name: 'q6',
            label:
                'Taxi Technique / Assistance / ATC Compliance / Before Takeoff Check',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 2,
            gradeSection: 2,
            posXList: _gradePosX,
            posY: 305),
        Field(
            name: 'qb_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 2,
            gradeSection: 2,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 279,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q7',
            label: 'Takeoff Technique / Rotation Rate / Takeoff Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 333),
        Field(
            name: 'q8',
            label: 'Cross Wind Takeoff / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 346),
        Field(
            name: 'q9',
            label: 'Rejected Takeoff at a reasonable speed before reaching V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 360),
        Field(
            name: 'q10',
            label: 'Takeoff with Simulated Engine Failure / Fire at V2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 3,
            gradeSection: 3,
            posXList: _gradePosX,
            posY: 374),
        Field(
            name: 'qc_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 3,
            gradeSection: 3,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 334,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q11',
            label: 'SID - Standard Instrument Departure / RNAV SID',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 401),
        Field(
            name: 'q12',
            label:
                'STAR - Standard Terminal Arrival Route / RNAV STAR / Holding Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 415),
        Field(
            name: 'q13',
            label: '3D Approach to DH/A of 200 Feet or Higher',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 429),
        Field(
            name: 'q14_check',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.checkbox,
            listValue: ['RNP-RNAV', 'VOR', 'LOC'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [119, 177, 212],
            posY: 442),
        Field(
            name: 'q14_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14_check_2',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q14',
            label: '2D Approach.........down to the MDH/A',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 444),
        Field(
            name: 'q15',
            label: 'Manual Fly with / without Flight Director',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 458),
        Field(
            name: 'q16',
            label: 'Manual Fly with One Engine Inoperative',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 472),
        Field(
            name: 'q17_check',
            label: 'Approach Maneuvering .........',
            type: FieldType.checkbox,
            listValue: ['Visual Circuit', ' Circling Approach'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: [155, 219],
            posY: 484),
        Field(
            name: 'q17_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q17_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            stringValue: 'FALSE'),
        Field(
            name: 'q17',
            label: 'Approach Maneuvering',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 486),
        Field(
            name: 'q18',
            label:
                'PBN Operations (*): Normal and Non-normal Procedure (Loss of RNP)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 500),
        Field(
            name: 'q19',
            label: 'IR: Instrument Departure / Arrival / Approach',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 514),
        Field(
            name: 'q20',
            label:
                'Automation Policy Adherence: Use the Appropriate Level of Automation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 528),
        Field(
            name: 'q21',
            label: 'Weather Avoidance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 542),
        Field(
            name: 'q22',
            label: 'Approach Preparation / Briefing / TEM / NAVAIDS Setting',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 555),
        Field(
            name: 'q23',
            label: 'Descent and Approach Management / Aircraft Configuration',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 569),
        Field(
            name: 'q24',
            label: 'Stabilized Approach Criteria and Compliance',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 4,
            gradeSection: 4,
            posXList: _gradePosX,
            posY: 582),
        Field(
            name: 'qd_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 4,
            gradeSection: 4,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 402,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q25_check',
            label: 'Flight Controls ',
            type: FieldType.checkbox,
            listValue: [
              'Slats/Flaps System',
              'Control or Stick Fault',
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [124, 210],
            posY: 608),
        Field(
            name: 'q25_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q25',
            label: 'Flight Controls',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 611),
        Field(
            name: 'q26_check',
            label: 'Ice and Rain',
            type: FieldType.checkbox,
            listValue: [
              'Anti-Ice System Fault',
              'Pilot or Window Heat System Fault'
            ],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [117, 210],
            posY: 623),
        Field(
            name: 'q26_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q26_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q26',
            label: 'Ice and Rain',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 625),
        Field(
            name: 'q27_check',
            label: 'Pneumatic',
            type: FieldType.checkbox,
            listValue: [
              'Bleed System Fault or Leak',
            ],
            checkBoxValue: [
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: [110],
            posY: 638),
        Field(
            name: 'q27_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            stringValue: 'FALSE'),
        Field(
            name: 'q27',
            label: 'Pneumatic',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 5,
            gradeSection: 5,
            posXList: _gradePosX2,
            posY: 640),
        Field(
            name: 'qe_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 5,
            gradeSection: 5,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 611,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q28',
            label: 'Engine Fire and Decision Making',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 669),
        Field(
            name: 'q29',
            label: 'Engine Failures / Shutdown / Restart',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 682),
        Field(
            name: 'q30',
            label: 'Emergency Descent',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 696),
        Field(
            name: 'q31',
            label: 'Windshear at Takeoff / Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 710),
        Field(
            name: 'q32',
            label: 'TCAS TA Response (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 723),
        Field(
            name: 'q33',
            label:
                'TCAS RAs - TCAS Altitude crossing RAs / at Maximum altitude (*)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX2,
            posY: 739),
        Field(
            name: 'q34_check',
            label: 'Approaches to Stalls Recovery.........',
            type: FieldType.checkbox,
            listValue: ['Clean', 'Landing Configuration'],
            checkBoxValue: [
              defaultCheck,
              defaultCheck,
            ],
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: [179, 216],
            posY: 749),
        Field(
            name: 'q34_check_0',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            stringValue: 'FALSE'),
        Field(
            name: 'q34_check_1',
            type: FieldType.string,
            input: false,
            writePdf: false,
            isMandatory: false,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            stringValue: 'FALSE'),
        Field(
            name: 'q34',
            label: 'Approaches to Stalls Recovery',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 753),
        Field(
            name: 'q35',
            label: 'Pilot Incapacitation',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 766),
        Field(
            name: 'q36',
            label: 'Declaration of Emergency or Urgency',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            section: 3,
            subSection: 6,
            gradeSection: 6,
            posXList: _gradePosX,
            posY: 780),
        Field(
            name: 'qf_comment',
            label: 'Comment',
            type: FieldType.string,
            section: 3,
            subSection: 6,
            gradeSection: 6,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 670,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q37',
            label: 'Go Around / Missed Approach Procedure with all engines',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 111),
        Field(
            name: 'q38',
            label:
                'Go Around / Missed Approach Procedure with one engine failure',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 125),
        Field(
            name: 'q39',
            label: 'Rejected Landing below DH / MDH / After Touchdown',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 138),
        Field(
            name: 'q40',
            label: 'Go Around from Intermediate Altitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            posXList: _gradePosX,
            posY: 151),
        Field(
            name: 'qg_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 7,
            gradeSection: 7,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 110,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q41',
            label: 'Normal Landing / Landing Technique / Landing Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 179),
        Field(
            name: 'q42',
            label: 'Landing in Out-Of-Trim Position',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 192),
        Field(
            name: 'q43',
            label: 'Crosswind landings / Gusty Wind',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 206),
        Field(
            name: 'q44',
            label: 'Reduced Flaps Landing (Flap3 or less)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 220),
        Field(
            name: 'q45',
            label: 'Landing with Simulated Engine Failure (Critical Engine)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 234),
        Field(
            name: 'q46',
            label:
                'Landing Roll / After Landing / Parking / Securing Procedures',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 248),
        Field(
            name: 'q47',
            label: 'Pax Evacuation Procedures (*)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            posXList: _gradePosX,
            posY: 262),
        Field(
            name: 'qh_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 8,
            gradeSection: 8,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 180,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q48',
            label: 'Engine Failure before V1 RTO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 289),
        Field(
            name: 'q49',
            label: 'Engine Failure at Takeoff after V1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 303),
        Field(
            name: 'q50',
            label: 'One Engine ILS Approach Go-Around and Landing',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            posXList: _gradePosX,
            posY: 317),
        Field(
            name: 'qi_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 9,
            gradeSection: 9,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 290,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q51',
            label:
                'Crew Resource Management (CRM) / Assertiveness / Support Process',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 344),
        Field(
            name: 'q52',
            label: 'Threat & Error Management / Security & Safety Attitude',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 358),
        Field(
            name: 'q53',
            label: 'Public Address (PA)',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            posXList: _gradePosX,
            posY: 372),
        Field(
            name: 'qj_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 10,
            gradeSection: 10,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 344,
            width: 115,
            fontSize: 8),

        ///------------------------------------
        Field(
            name: 'q54',
            label: 'One Engine Taxi Procedure (In and Out)',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 399),
        Field(
            name: 'q55',
            label: 'Glide Slope Interception from Above',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 413),
        Field(
            name: 'q56',
            label: 'Overweight Landing',
            type: FieldType.radio,
            listValue: _gradeList2,
            intValue: defaultGrade(),
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX2,
            posY: 426),
        Field(
            name: 'q57_detail',
            label: 'Additional Exercises 1',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 442),
        Field(
            name: 'q57',
            label: 'Additional Exercises 1',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 439),
        Field(
            name: 'q58_detail',
            label: 'Additional Exercises 2',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            textCapitalization: TextCapitalization.sentences,
            stringValue: Authen.isTjo() ? 'Additional...' : '',
            posX: 64,
            posY: 455),
        Field(
            name: 'q58',
            label: 'Additional Exercises 2',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            isMandatory: false,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            posXList: _gradePosX,
            posY: 452),
        Field(
            name: 'qk_comment',
            label: 'Comment',
            type: FieldType.string,
            page: 2,
            section: 3,
            subSection: 11,
            gradeSection: 11,
            isMandatory: false,
            maxLength: gradeCommentMaxLen,
            stringValue: defaultComment,
            posX: 445,
            posY: 399,
            width: 115,
            fontSize: 8),

        ///.....................................................................
        ///Number of Manual Landing and Go-Around
        ///.....................................................................
        Field(
            name: 'no_landing',
            label: 'Number of Manual Landing',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 230,
            posY: 473),
        Field(
            name: 'no_goaround',
            label: 'Number of Go-around',
            type: FieldType.string,
            page: 2,
            section: 4,
            subSection: 1,
            keyboardType: TextInputType.number,
            stringValue: Authen.isTjo() ? '2' : '',
            posX: 492,
            posY: 473),

        ///.....................................................................
        ///Competency Assessment and Comments
        ///.....................................................................
        Field(
            name: 'comp_kno',
            label: 'KNO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 519),
        Field(
            name: 'comp_pro',
            label: 'PRO',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 532),
        Field(
            name: 'comp_com',
            label: 'COM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 545),
        Field(
            name: 'comp_fpa',
            label: 'FPA',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 558),
        Field(
            name: 'comp_fpm',
            label: 'FPM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 569),
        Field(
            name: 'comp_ltw',
            label: 'LTW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 582),
        Field(
            name: 'comp_psd',
            label: 'PSD',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 595),
        Field(
            name: 'comp_saw',
            label: 'SAW',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 608),
        Field(
            name: 'comp_wlm',
            label: 'WLM',
            type: FieldType.radio,
            listValue: _gradeList,
            intValue: defaultGrade(),
            page: 2,
            section: 5,
            subSection: 1,
            posXList: _gradePosX,
            posY: 621),
        Field(
            name: 'general_comment',
            label: 'General Comment',
            type: FieldType.string,
            stringValue: defaultComment,
            page: 2,
            section: 5,
            subSection: 1,
// isMandatory: false,
            maxLength: 500,
            posX: 42,
            posY: 521,
            width: 260,
            height: 100,
            fontSize: 8),

        ///.....................................................................
        ///OVERALL GRADING
        ///.....................................................................
        Field(
            name: 'result',
            label: 'Result',
            type: FieldType.radio,
            listValue: [
              '(1) Unsatisfactory',
              '(2) Improvement Required',
              '(3) Company Standard',
              '(4) Effective',
              '(5) Precise',
            ],
            intValue: defaultGrade(),
            page: 2,
            section: 6,
            subSection: 1,
            posXList: [138, 226, 339, 441, 505],
            posY: 650),

        ///.....................................................................
        ///Signature
        ///.....................................................................
        Field(
            name: 'pilot_sig',
            label: 'Trainee\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 75,
            posY: 738),
        Field(
            duplicateFrom: 'pilot_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 70,
            posY: 764),
        Field(
// name: 'pilot_sig_date',
// label: 'Date',
            type: FieldType.date,
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
// keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
// stringValue:
//     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
// dateTimeValue: DateTime.now(),
            posX: 70,
            posY: 774),
        Field(
            name: 'instructor_sig',
            label: 'Instructor\'s Signature',
            type: FieldType.signature,
            sigWidth: 80,
            sigMaxHeight: 50,
            page: 2,
            section: 7,
            posX: 245,
            posY: 738),
        Field(
            duplicateFrom: 'instructor_name',
            isMandatory: false,
            input: false,
            type: FieldType.string,
            page: 2,
            section: 7,
            posX: 245,
            posY: 764),
        Field(
// name: 'instructor_sig_date',
// label: 'Date',
            duplicateFrom: 'check_date',
            isMandatory: false,
            input: false,
            type: FieldType.date,
// keyboardType: TextInputType.datetime,
            page: 2,
            section: 7,
// stringValue:
//     DateFormat('dd MMM yyyy').format(DateTime.now()).toUpperCase(),
            dateTimeValue: DateTime.now(),
            posX: 245,
            posY: 774),
      ],
    );
  }

  static Map<String, dynamic> toMap(f.Form form) {
      return {
        ///----------------------------------------------------------------------
        ///HEADER
        ///----------------------------------------------------------------------
        ///Form info.
        'status': form.status.toString(),
        'type': form.type.toString(),
        'form_name': form.formName,
        'create_at': form.createDateTime.toString(),
        'submit_at': form.submitDateTime != null ? form.submitDateTime.toString() : '',
        'create_by': form.createBy,
        'file_path': form.filePath,
        'id': form.id,
        'font_size': form.fontSize.round().toString(),
        'pdf_url': form.pdfUrl ?? '',

        ///----------------------------------------------------------------------
        ///ITEM
        ///----------------------------------------------------------------------
        ///Pilot info.
        'pilot_rank': form.getStrVal('pilot_rank'),
        'pilot_name': form.getStrVal('pilot_name'),
        'pilot_license_no': form.getStrVal('pilot_license_no'),
        'pilot_id': form.getStrVal('pilot_id'),

        ///Instructor info.
        'instructor_rank': form.getStrVal('instructor_rank'),
        'instructor_name': form.getStrVal('instructor_name'),
        'instructor_cert_no': form.getStrVal('instructor_cert_no'),
        'instructor_id': form.getStrVal('instructor_id'),

        ///Check details
        'check_date': form.getStrVal('check_date'),
        'block_time': form.getStrVal('block_time'),
        'fstd_no': form.getStrVal('fstd_no'),
        'ac_type': form.getStrVal('ac_type'),
        'route': form.getStrVal('route'),
        'rhs': form.getStrVal('rhs'),
        'loft_duty': form.getStrVal('loft_duty'),

        ///Grading & Comment
        ///A
        'q1': form.getStrVal('q1'),
        'q2': form.getStrVal('q2'),
        'q3': form.getStrVal('q3'),
        'q4': form.getStrVal('q4'),
        'q5_detail': form.getStrVal('q5_detail'),
        'q5': form.getStrVal('q5'),
        'q6': form.getStrVal('q6'),
        'q7': form.getStrVal('q7'),
        'q8': form.getStrVal('q8'),
        'q9': form.getStrVal('q9'),
        'q10': form.getStrVal('q10'),
        'q11': form.getStrVal('q11'),
        'q12': form.getStrVal('q12'),
        'q13': form.getStrVal('q13'),
        'q14_check_0': form.getStrVal('q14_check_0'),
        'q14_check_1': form.getStrVal('q14_check_1'),
        'q14_check_2': form.getStrVal('q14_check_2'),
        'q14': form.getStrVal('q14'),
        'q15': form.getStrVal('q15'),
        'q16': form.getStrVal('q16'),
        'q17_check_0': form.getStrVal('q17_check_0'),
        'q17_check_1': form.getStrVal('q17_check_1'),
        'q17': form.getStrVal('q17'),
        'q18': form.getStrVal('q18'),
        'q19': form.getStrVal('q19'),
        'q20': form.getStrVal('q20'),
        'q21': form.getStrVal('q21'),
        'q22': form.getStrVal('q22'),
        'q23': form.getStrVal('q23'),
        'q24': form.getStrVal('q24'),
        'q25_check_0': form.getStrVal('q25_check_0'),
        'q25_check_1': form.getStrVal('q25_check_1'),
        'q25': form.getStrVal('q25'),
        'q26_check_0': form.getStrVal('q26_check_0'),
        'q26_check_1': form.getStrVal('q26_check_1'),
        'q26': form.getStrVal('q26'),
        'q27_check_0': form.getStrVal('q27_check_0'),
        'q27': form.getStrVal('q27'),
        'q28': form.getStrVal('q28'),
        'q29': form.getStrVal('q29'),
        'q30': form.getStrVal('q30'),
        'q31': form.getStrVal('q31'),
        'q32': form.getStrVal('q32'),
        'q33': form.getStrVal('q33'),
        'q34_check_0': form.getStrVal('q34_check_0'),
        'q34_check_1': form.getStrVal('q34_check_1'),
        'q34': form.getStrVal('q34'),
        'q35': form.getStrVal('q35'),
        'q36': form.getStrVal('q36'),
        'q37': form.getStrVal('q37'),
        'q38': form.getStrVal('q38'),
        'q39': form.getStrVal('q39'),
        'q40': form.getStrVal('q40'),
        'q41': form.getStrVal('q41'),
        'q42': form.getStrVal('q42'),
        'q43': form.getStrVal('q43'),
        'q44': form.getStrVal('q44'),
        'q45': form.getStrVal('q45'),
        'q46': form.getStrVal('q46'),
        'q47': form.getStrVal('q47'),
        'q48': form.getStrVal('q48'),
        'q49': form.getStrVal('q49'),
        'q50': form.getStrVal('q50'),
        'q51': form.getStrVal('q51'),
        'q52': form.getStrVal('q52'),
        'q53': form.getStrVal('q53'),
        'q54': form.getStrVal('q54'),
        'q55': form.getStrVal('q55'),
        'q56': form.getStrVal('q56'),
        'q57_detail': form.getStrVal('q57_detail'),
        'q57': form.getStrVal('q57'),
        'q58_detail': form.getStrVal('q58_detail'),
        'q58': form.getStrVal('q58'),

        'qa_comment': form.getStrVal('qa_comment'),
        'qb_comment': form.getStrVal('qb_comment'),
        'qc_comment': form.getStrVal('qc_comment'),
        'qd_comment': form.getStrVal('qd_comment'),
        'qe_comment': form.getStrVal('qe_comment'),
        'qf_comment': form.getStrVal('qf_comment'),
        'qg_comment': form.getStrVal('qg_comment'),
        'qh_comment': form.getStrVal('qh_comment'),
        'qi_comment': form.getStrVal('qi_comment'),
        'qj_comment': form.getStrVal('qj_comment'),
        'qk_comment': form.getStrVal('qk_comment'),

        ///LANDING AND GO-AROUND
        'no_landing': form.getStrVal('no_landing'),
        'no_goaround': form.getStrVal('no_goaround'),

        ///COMPETENCY
        'comp_kno': form.getStrVal('comp_kno'),
        'comp_pro': form.getStrVal('comp_pro'),
        'comp_com': form.getStrVal('comp_com'),
        'comp_fpa': form.getStrVal('comp_fpa'),
        'comp_fpm': form.getStrVal('comp_fpm'),
        'comp_ltw': form.getStrVal('comp_ltw'),
        'comp_psd': form.getStrVal('comp_psd'),
        'comp_saw': form.getStrVal('comp_saw'),
        'comp_wlm': form.getStrVal('comp_wlm'),
        'general_comment': form.getStrVal('general_comment'),

        ///RESULT
        'result': form.getStrVal('result'),
// 'pilot_sig_date': form.getStrVal('pilot_sig_date'),
// 'instructor_sig_date': form.getStrVal('instructor_sig_date'),
      };
  }
}
